### ISSUE TITLE
MainPower missing / Auto mode not working for HP02

### ISSUE THREAD

**Issue by palood** [Grizzelbee/ioBroker.dysonairpurifier#105]
Hi,

ich habe gerade die Version 0.9.0 installiert und freue mich, dass der Adapter nun wieder läuft.

Leider vermisse ich noch weiterhin den Datenpunkt im ioBroker "MainPower".
Ich kann das Gerät steuern, jedoch nur, wenn es bereits eingeschaltet ist.
Weiterhin funktioniert leider nicht der Auto-Mode. Ich kann den FanSpeed ändern, "Auto" hat jedoch keine Auswirkung.
Im Falle "Auto" wird laut Log "{"fnsp":"AUTO","auto":"ON"}" an das Gerät gesendet.

JS-Controller: 3.2.16
Firmware Dyson: 21.04.03
Gerät: Dyson Pure Hot+Cool Link (HP02, ProductType 455)

**Comment by Grizzelbee** [comment]
Duplicate to #97

**Comment by Grizzelbee** [comment]
Allem Anschein nach ist die Steuerung der Lüfter über alle Modelle nicht ganz konsistent. Sachen die bei einem Modell funktionieren, funktionieren bei einem anderen nicht, obschon die gleichen Steuertoken verwendet werden.
In deinem Fall musst du bitte den in v0.9.1 geänderten FanMode verwenden.
