### ISSUE TITLE
XXXX.Sensor.Temperature" has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by tery29** [Grizzelbee/ioBroker.dysonairpurifier#107]
Nabend!

Ich bekomme ständig den Fehler, der mülllt mir das Log zu.
Kann ich daran was ändern?
V.0.9.1 ist installiert.

Viele Grüße

**Comment by Grizzelbee** [comment]
Korrigiere ich in der nächsten Version.

**Comment by Grizzelbee** [comment]
Was für ein Gerät hast Du? Ich habe keine Einträge im Log.

**Comment by tery29** [comment]
> Was für ein Gerät hast Du? Ich habe keine Einträge im Log.

Hi Grizzelbee : Dyson Pure Cool Turmventilator mit Luftreiniger Weiß/Silber

**Comment by Grizzelbee** [comment]
> Dyson Pure Cool Turmventilator mit Luftreiniger Weiß/Silber
 Das passt leider auf 2/3 aller Modelle. Gib mir bitte mal die Zahl, die im Adapter unter productType steht. Und am besten mal einen Logauszug vom Start des Adapter bis zum "Fehler".

**Comment by tery29** [comment]
Hallo Grizzlebee, sorry die verspätete Antwort:

Producttype : 438

https://pastebin.com/shxk6kZY

**Comment by Grizzelbee** [comment]
<html><body>


dysonairpurifier.0 | 2432 | 2021-08-19 15:21:30.468 | info | State  value to set for  "dysonairpurifier.0.xxx.Sensor.Temperature" has to be type  "number" but received type "string"
-- | -- | -- | -- | --



</body>
</html>
