### ISSUE TITLE
bitte AT hinzufügen

### ISSUE THREAD

**Issue by krobipd** [Grizzelbee/ioBroker.dysonairpurifier#11]
hallo

hab durch zufall deinen adapter gefunden, großartig!
bitte füge doch AT in den Countrycode mit ein, damit könnte ich ihn testen.
in der Länderauswahl gibt es nur Deutschland :-/
wirft direkt haufenweiße fehlermeldungen wie zB
`

(10792) Error during dyson API login:Error: unable to verify the first certificate, Callstack: Error: unable to verify the first certificate
--

`

hab einen humidify+cool

**Comment by Grizzelbee** [comment]
Ich arbeite gerade an einer neuen Version, die wird das AT mitbringen.

Den Fehler, den Du da bekommst, bekommen gerade alle Neuanmeldungen. Da muss ich nach schauen. Keine Ahnung ob oder wie ich das gefixed bekomme. Für mich siehst das auf den ersten Blick so aus, als hätte dyson etwas an seiner API geändert.

**Comment by Grizzelbee** [comment]
Fixed in 0.4.1 (2020-10-16).
Please close this issue, when it's working for you.

**Comment by krobipd** [comment]
Super vielen Dank, Verbindung läuft. Alles super geklappt. Werden den Adapter dann die nächsten Tage testen. Danke für deine Mühe.
