### ISSUE TITLE
Dyson TP07 falsche NO2 werte.

### ISSUE THREAD

**Issue by Phillipp83** [Grizzelbee/ioBroker.dysonairpurifier#113]
Hallo Grizzelbiene,
Ich habe den TP07 und mir ist aufgefallen das die NO2 Werte im IOBroker anders sind als in der Dyson app. 
Ich habe mal zwei Bilder hinzugefügt. 

Gruß Phillipp

![Dyson app](https://user-images.githubusercontent.com/58390332/122566557-f4029f00-d047-11eb-94b3-99d1fd0af541.jpeg)
![ioBroker](https://user-images.githubusercontent.com/58390332/122566560-f49b3580-d047-11eb-92a8-74a40c323089.jpg)

**Comment by Grizzelbee** [comment]
Hallo Philipp,

Hmmm. Ich stimme dir vollkommen zu, das die Werte abweichen ... bin aber noch nicht sicher, was ich da machen kann/soll.
dyson macht zum Beispiel bei VOC auch komische Dinge: Die Skala in der App geht von 0-9+. Der Sensor liefert aber Werte von 0-99. In dem Fall habe ich beschlossen die Skala im Adapter entsprechend der Sensorwerte anzupassen. Gut möglich, das die bei NO2 die Werte auch irgendwie gruppieren. Ich schreibe jedenfalls genau das raus, was der Sensor liefert. Ob das sinnvoll ist müssen wir mal im Auge behalten und ggf. anpassen.

**Comment by Grizzelbee** [comment]
Die Werte werden in der kommenden Version 3.1.0 gefixed werden und analog zur App funktionieren.
