### ISSUE TITLE
Country Code for Switzerland Missing

### ISSUE THREAD

**Issue by phifogg** [Grizzelbee/ioBroker.dysonairpurifier#114]
I operate my Dyon in Switzerland and would want to select this country code :)

I also learned (the hard way) that requesting the 2FA code only works with a country selected. Would be good to mention that somehow.

**Comment by Grizzelbee** [comment]
>I operate my Dyon in Switzerland and would want to select this country code :)

I'll be happy to add countrycodes für switzerland in the next release.


> I also learned (the hard way) that requesting the 2FA code only works with a country selected. Would be good to mention that somehow.

It is actually mentioned in the readme (loud and clearly 😉  ) ...
But I'll think about integrating it in the config window as well.

![grafik](https://user-images.githubusercontent.com/5459426/122776878-c9188500-d2ab-11eb-94e8-7d8139a9551b.png)

**Comment by phifogg** [comment]
Readme... who reads them anyway? ;D

I was just installing from within ioBroker modules and off we go...
Since it is installed it seems it locked my dyson account. I guess this is due to the wrong country code. Currently I cannot even login from my dyson app :/

**Comment by Grizzelbee** [comment]
> Readme... who reads them anyway? ;D

Basically I agree. But in case of issues...

> Since it is installed it seems it locked my dyson account. I guess this is due to the wrong country code. Currently I cannot even login from my dyson app :/
Please try removing the app from your mobile device and reinstall it. Hope that helps. Or try unlocking the account via dyson homepage.

**Comment by phifogg** [comment]
Thanks, I was chatting with the Dyson support to get the login to work. Turns out the app login is not the same as the website. So effectively two different passwords. good to know.
