### ISSUE TITLE
keine Verbindung zum Dyson Pure Cool Link™ möglich

### ISSUE THREAD

**Issue by fullcavediver** [Grizzelbee/ioBroker.dysonairpurifier#115]
Ich kann keine Verbindung zu meinem Dyson Pure Cool Link™ Turmluftreiniger aufbauen. Über die Dyson Cloud ist er aber erreichbar - die gleichen Zugangsdaten. Der ioBroker Adapter wird nicht gestartet. Ich verwende keine 2FA weil ich auf der Seite dyson.at keine Möglichkeit gefunden habe, sie zu konfigurieren. Wie kann ich herausfinden, wo das Problem liegt? Da ich über die Dyson Cloud auf das Gerät zugreifen soll, ist es wahrscheinlich nicht notwendig, die IP Adresse in der Konfiguration einzugeben. Es gibt für sie auch keinen Eingabefeld im Adapter.

**Comment by Grizzelbee** [comment]
Hi!

> Ich kann keine Verbindung zu meinem Dyson Pure Cool Link™ Turmluftreiniger aufbauen. Über die Dyson Cloud ist er aber erreichbar - die gleichen Zugangsdaten. Der ioBroker Adapter wird nicht gestartet. Ich verwende keine 2FA weil ich auf der Seite dyson.at keine Möglichkeit gefunden habe, sie zu konfigurieren. 

Offenbar nutzt du ein "altes" dyson Konto. Will sagen: dyson hat die 2FA Authentifizierung erst im März diesen Jahres für neue Anmeldungen eingeführt. Wenn du die Handy-App schon vorher installiert hattest  hast du die Einführung nicht bemerkt. Wenn du die App jetzt deinstallierst und neu installierst, wirst du durch den selben Prozess geschickt, den der Adapter jetzt auch mit dir macht. Also zusammengefasst: Du nutzt sehr wohl 2FA, bist dir darüber nur nicht im Klaren, weil dyson das unter der hand eingeführt hat. Du musst dafür auch nichts bei dyson konfigurieren, durlaufe euinfach den Prozess und dann sollte alles gut werden.


> Wie kann ich herausfinden, wo das Problem liegt? 

siehe oben - und unten. 😉 

> Da ich über die Dyson Cloud auf das Gerät zugreifen soll, ist es wahrscheinlich nicht notwendig, die IP Adresse in der Konfiguration einzugeben. Es gibt für sie auch keinen Eingabefeld im Adapter.

Das stimmt so nicht. Der Adapter braucht (grob gesprochen) die dyson-cloud nur um abzufragen welche Geräte deinem Konto zugeordnet sind. Die Kommunikation mit den Geräten selbst findet komplett lokal über mqtt statt. Dafür benötigt der Adapter aber sehr wohl die Hostadresse des Gerätes. Dafür ist das gleichnamige Feld vorgesehen. Da es sich dabei aber nicht zwingend um eine IP-Adresse handeln muss, habe ich den etwas allgemeineren Begriff verwendet. Wenn nämlich ein lokaler DNS vorhanden oder die HOSTS-Datei auf der entsprechenden Maschine gepflegt ist, lässt sich jedes Gerät auch über seinen Hostnamen ansprechen. Im Falle der dyson-Geräte ist das standartmäßig deren Seriennummer (Werksseitig, wenn man das nicht geändert hat). Ich nutze das sogar aktiv im Adapter aus und versuche die Geäte so zu finden. Sollte das nicht klappen, gibt es eine entsprechende Meldung im Log.

Zusammenfassung:
* Führe bitte die vorgegebenen Schritte für die 2FA aus (Btw: Ich weiß das "echte" 2FA etwas anders aussieht). Im Ergebniss bekommst du einfach nur zusätzlich zu deinen Credentials einen Token über den du dich autentifizierst.
* Versuche den Adapter danach zu starten. Sollte das nicht klappen - schaue ins Log, was da so steht. Ggf. musst du deine IP noch eingeben. Wenn du einen lokalen DNS (z.B. in einer Fritzbox) hast, sollte das nicht notwendig sein.

**Comment by fullcavediver** [comment]
Hallo @Grizzelbee , vielen Dank für diene ausführliche Antwort und deine Hilfe. Jetzt bin ich schon einen Schritt weiter. Scheinbar wird 2FA erst dann aktiviert, nachdem du dich zumindest ein mal aus der App ausgeloggst hast. Jetzt habe ich tatsächlich ein E-Mail mit Code bekommen und auch der Button "2FA-CODE-EMAIL" hat diesmal funktioniert. Toll! Danke!
Ich habe mir erst vor zwei Tagen ein Account bei Dyson angelegt und das war das erste Gerät, das ich hinzugefügt habe. Bei der Erstanmeldung gab es definitiv keine 2FA-Code-Eingabe - ich habe alle meine E-Mails vom 23.06.2021 durchgestöbert - kein Code wurde zugesendet.

Trotzdem sehe ich keine Möglichkeit in der App die IP-Adresse einzugeben:
![2021-06-25_070406](https://user-images.githubusercontent.com/49302111/123375406-01a8af00-d589-11eb-876d-5e05215b4b25.png)

Vielleicht sollte der ioBroker Adapter alle Geräte in seinem LAN selbst finden und das ist mein Problem. Meine IoT Geräte, die Cloud-Anbindung brauchen, sind im Gäste LAN und dürfen lt. Policy nur ins Internet. In meinem privaten Netzwerk habe ich nur Shelly (ohne Cloud-Anbindung) und Tasmota, weil ich diesen vertraue ;-) Wenn der Purifier mit dem Adapter über MQTT kommuniziert, dann muss ich ihm irgendwie sagen, welche IP Adresse der ioBroker hat und welche Portnummer er verwenden soll. Ich habe mittlerweile schon einen MQTT Server laufen für die Tasmota Geräte - also der Standard-Port 1883 ist belegt. Ganz blöde Frage - wenn ich den Purifier direkt über MQTT anbinden kann, muss ich wirklich die Cloud verwenden? Ich bin kein Fun von fremden Clouds. Gut, Dyson ist nicht in China (hoffentlich) und hat 2FA eingeführt - das ist schon ein Fortschritt. Siehst du hier eine Möglichkeit, mein Gerät zu verbinden, oder muss ich es ins private LAN übersiedeln? Solange ich nur noch ein weiteres IoT Gerät habe, das Cloud benötigt und nicht unbedingt über ioBroker gesteuert werden muss, möchte ich nicht unbedingt ein weiteres LAN-Segment aufbauen. Ich bin für alle Ratschläge sehr dankbar.

LGc

**Comment by Grizzelbee** [comment]
Also ... noch eine länliche Erklärung: 😉 
1. Bitte einfach mal die Readme lesen. Es gibt durchaus Gründe warum die ist, wie sie ist und mehr als nur den Projektnamen und das Changelog enthält (wie in manch anderem Projekt). Der Foren-Thread (https://forum.iobroker.net/topic/37200/dyson-air-purifier-adapter-tester-gesucht) enthält auch jede Menge Hintergrundwissen und ist noch recht überschaubar, bitte ebenfalls mal scannen.
2. Der dyson funktioniert wie er funktioniert - da kann ich nichts dran ändern. Das bedeutet: ich werde es mit diesem Adapter nicht jedem Recht machen können und nicht auf jede Sonderkonfig eingehen können - ich muss mich an die Funktionsweise halten, die dyson vorgibt und die ich reverse-engeneeren kann, denn Unterstützung von dyson bekomme ich nicht (Ja - ich habe danach gefragt).

Zur Funktionsweise:
dyson speichert ein paar Eckdaten (Seriennummer, Firmware-Infos, ...) und die mqtt Credentials zu jedem Gerät in der Cloud. Dafür (und NUR dafür) benötige ich (= der Adapter) den Login an der Cloud. Das wird bei jedem Start des Adapters ein mal abgefragt - danach findet KEINE Kommunikation mehr mit der Cloud statt (nicht zuletzt weil ich das nicht reverse engeneeren kann). *Selbst wenn ich es wollte, könnte ich die Geräte nicht über die dyson-cloud steuern.* Deshalb findet der Adapter neue Geräte auch nur nach einem Neustart. Da der Adapter beliebig viele Geräte verwalten kann, muss die IP also bei jedem Gerät individuell *im Objektbaum* hinterlegt werden. 
Für die Kommunikation mit jedem Netzwerkgerät ohne Cloud müssen sich der ioBroker und das Gerät selbst im gleichen Subnetz befinden (oder über routen finden können) - deshalb wird dein aktuelles Setup so nicht funktionieren. Du musst dich also entscheiden ob du dyson auf der eiinen und meinem Adapter auf der anderen Seite vertrauen willst, oder nicht.
Ich stimme dir aber zu, dass das durchaus ein Thema ist über das man sich Gedanken machen sollte. Deshalb halte ich das ähnlich wie Du: Tasmota und Miele vertraue ich, Shelly muss notgedrungen (würde ich bei einem Neustart aber eher mit Zigbee machen), ... Den Ansatz den ioBroker ins lokale Netz zu packen und nur die Geräte zu isolieren (wie ich es schon ein paar mal gelesen habe) finde ich allerdings merkwürdig...

**Comment by fullcavediver** [comment]
wenn sich des Gerät in einem geroutetem Netzwerk befinden kann, dann ist das auch schon eine Lösung. Wo kann ich die IP Adresse eintragen? Kann ich den Standardport 1883 ändern?

**Comment by Grizzelbee** [comment]
Wie schon geschrieben: Im Objektbaum unter Hostadress:

![grafik](https://user-images.githubusercontent.com/5459426/123391094-f27f2c80-d59b-11eb-8431-1cea0494f7b2.png)

**Comment by fullcavediver** [comment]
sorry, meine Frage war zu unpräzise, wo kann ich in dem Purifier die IP-Adresse des MQTT Server (ioBroker) eintragen und kann ich den MQTT Port ändern? Du schreibst von DNS Namen oder IP-Adresse - ich finde kein Eingabefeld dafür. Tasmota hat ein WEB Interface für die Eingabe - bei Purifier habe ich keine offenen Ports gefunden. Die IP-Adresse des Purifier habe ich über den Router herausgefunden, das ist nicht das Problem, aber er weiss nicht, wo er seine Daten per MQTT schicken soll

**Comment by Grizzelbee** [comment]
Du hast dich gedankllich vertüddelt. 😉 

Du kannst die dysons nicht an deinen MQTT Server anbinden - das wäre eine Server-zu-Server-Kopplung.

> Tasmota hat ein WEB Interface für die Eingabe - bei Purifier habe ich keine offenen Ports gefunden. Die IP-Adresse des Purifier habe ich über den Router herausgefunden, das ist nicht das Problem, aber er weiss nicht, wo er seine Daten per MQTT schicken soll.

Die dyson Geräte machen jeder einen eigenen MQTT-Server auf und kommunizieren bidirektional mit dem Adapter. Sprich: Der Adapter ist der Client (je einer zu jedem verwalteten Gerät). Deshalb spielt der Port auch keine Rolle und das du bereits einen MQTT auf einer anderen IP hast. Es funktioniert also genau anders herum, als du es gerade versuchst. Und : JA - die Kommunikation mit der Cloud wird benötigt um die Login-Credentials für die in den Geräten integrierten MQTT-Server abzufragen - ohne die geht das nicht.

>Läuft dein Sonoff Adapter (für Tasmota Geräte) auf dem Standard-Port?

Ich habe bei mir einfach den SonOff und den dyson Adapter parallel laufen ohne irgendwelche Port Einstellungen gemacht zu haben (alles dafault) und ohne das etwas in Konflikt gerät.

> wo kann ich in dem Purifier die IP-Adresse des MQTT Server (ioBroker) eintragen und kann ich den MQTT Port ändern?

Also: Der dyson hat keinerlei Konfig-Möglichkeiten. An dem kannst Du nichts einstellen (musst du aber auch nicht) - du musst das nehmen, wie es ist. Deine aktuellen Probleme ergeben sich nur daraus, das du gegen die Funktionsweise anarbeitest.

> Du schreibst von DNS Namen oder IP-Adresse - ich finde kein Eingabefeld dafür. 

Das Eingabefeld für die IP habe ich im Screenshot oben rot markiert.

**Comment by fullcavediver** [comment]
ok, jetzt habe ich es verstanden! Dyson Geräte sind MQTT Server, das ändert natürlich alles. Jetzt brauche ich nur noch die Möglichkeit dem Adapter zu sagen - der Purifier hat die Adresse 192.168.66.105. Wo mache ich das? In dem Adapter sehe ich kein Eingabefeld. Der ioBroker hat die Adresse 192.168.65.55 - sie sind also in anderen Netzen, ich kann den Purifier aber per ICMP erreichen (ping)

**Comment by Grizzelbee** [comment]
> Jetzt brauche ich nur noch die Möglichkeit dem Adapter zu sagen - der Purifier hat die Adresse 192.168.66.105. 

siehe Screenshot. Das Feld wird angelegt!

> Wo mache ich das? In dem Adapter sehe ich kein Eingabefeld.

Im Adapter (also der generischen Adapter-Konfig) **kann** das nicht sein, weil der Adapter, wie gesagt, viele Geräte verwalten kann.

> Die Objekte sehe ich nicht, solange ich keine Verbindung zum Gerät aufbauen konnte.

Die Basis-Infos aus der Cloud und das Hostname Feld werden vor der Verbindunng mit den Geräten angelegt - muss ja auch, weil du sonst ja keine IP eingeben könntest.

**Comment by fullcavediver** [comment]
Danke! Ich habe es zum Laufen gebracht! Die Information, dass das Gerät selbst ein MQTT Server ist, war das entscheidende.

Wichtig: das Gerät muss sich (zumindest bei der Erstinstallation) in dem selben Netzwerk befinden, in dem auch ioBroker steht, sonst bekommt man kein API key und es werden keine Objekte angelegt - so war es zumindest bei mir. Vielleicht war ich zu ungeduldig, ich habe es aber öfters probiert. Danach wird der Adapter zwar immer noch auf "gelb", aber es werden die ersten Objekte übertragen - das wichtigste - Eingabefeld für die IP-Adresse oder DNS Namen. Nachdem der Name eingetragen wird und der Adapter restartet wird - wechselt er seinen Status auf "grün" und alle Parameter/Objekte werden übertragen.

Ich habe nicht probiert, ob ich ihn jetzt in ein anderes LAN verlegen kann, aber das ist jetzt für mich nebensächlich. Nachdem er per MQTT mit dem ioBroker kommuniziert, kann er im privaten LAN bleiben.

Vielen Dank nochmal für deine tolle Unterstützung!
