### ISSUE TITLE
Registration process cannot be completed

### ISSUE THREAD

**Issue by DannySotzny** [Grizzelbee/ioBroker.dysonairpurifier#117]
After the installation in ioBroker I cannot finish the registration process because the buttons to request the code do not react. According to the web console, the following script cannot be loaded either:
`/adapter/dysonairpurifier/dyson-utils.js`

Version:   0.9.1

**Comment by Grizzelbee** [comment]
Hmm. Sounds like the file hasn't been installed. 
Please try reinstalling (and maybe removing the adapter prior to this) the adapter - since this file is really essentially needed. Not only for the registration process.

**Comment by DannySotzny** [comment]
That´s really strange.
I even had the version from Githab installed... but it still grumbles around the file would not be there.

In the file system under /opt/iobroker/node_modules/iobroker.dysonairpurifier is the file... and had it also once copied to admin/ but he also does not find.

But also strange: if i delete the admin/dyson_logo.svg i can still retrieve it?! locate finds the file but only at that location.

Now I have really uninstalled the adapter again properly via the UI and reinstalled. and there you can also see that the file is not uploaded with. but in the file system it is there. (Use redis as backend - therefore perhaps?)
![image](https://user-images.githubusercontent.com/14806755/126470359-839a1cb2-04e6-4643-9061-9797b4bf8b6b.png)

Now I really uninstalled the adapter again properly via the UI and reinstalled. and there you can also see that the file is not uploaded with. but in the file system it is there. (Use redis as backend - therefore maybe?).

Have the dyson-util.js now times copied to admin/ and then called "iobroker upload dysonairpurifier" and there it uploads it and then the link also works.

But still nothing happens when I press one of the two buttons :-(

**Comment by Grizzelbee** [comment]
Hmm. Have you read the readme.md@github esp. the part regarding prerequisites, installing and 2fa process?

It starts to sound to me like you are trying to install the adapter without having an active dyson-account.

**Comment by Grizzelbee** [comment]
Okay. Seem to be solved. Closing therefor. Reopen if needed.
