### ISSUE TITLE
Seit  js-controller update lässt sich der Adapter nicht mehr Starten.

### ISSUE THREAD

**Issue by Phillipp83** [Grizzelbee/ioBroker.dysonairpurifier#119]
Hallo,
Ich habe heute mein IOBroker auf js-controller: 3.3.15 upgedatet. 

Nach dem update habe ich die Info in meinem Log gehabt.

> (23949)` [main()] error: undefined, stack: undefined

Ich habe dann versucht eine neue 2-Faktor-Authentifizierungs E-Mail anzufordern.

In den Log's bekomme ich dann die Meldung 

> (23949) getDyson2faMailError: unable to verify the first certificate

wenn du das auch noch brauchst Node.js: v12.22.4
NPM: 6.14.14
Dyson adapter ver. 0.9.1

MFG
Phillipp

**Comment by Reventrop** [comment]
Selbes Problem

**Comment by krobipd** [comment]
Hab das selbe Problem

**Comment by ccsbonn** [comment]
same here...

**Comment by viper4gh** [comment]
Ich habe auch die Meldung:
[main()] error: undefined, stack: undefined

Allerdings hatte das bei mir nichts mit dem js-controller Update zu tun.
Dieses Update wollte ich auch durchführen und habe deshalb ein manuelles Backup vom kompletten iobroker gemacht.
Dazu stoppe ich ihn komplett und starte ihn nach dem Backup wieder.
Und genau da hatte ich schon den Fehler, bevor ich überhaupt zum Update kam.

Könnte also sein, dass das js-controller Update nur den Adapter neu gestartet hat und da nur beim Start des Adapters zentral auf Dyson zugegriffen, funktioniert er jetzt aus irgendeinem Grund nicht mehr.
Liegt also eventuell nicht am js-controller Update, sondern Dyson hat mal wieder etwas an der API geändert.

**Comment by krobipd** [comment]
Ja mein Problem kam auch von jetzt auf gleich und hatte nichts mit einem Update seitens iobroker zu tun.

ich hab mich jetzt mal bei anderen Dyson Anbindungen umgesehen und so wie es mir erscheint hat Dyson an der Verschlüsselung gedreht.

das hier dürfte wohl ein passender Ansatz sein.
https://github.com/shenxn/libdyson/pull/14

**Comment by Grizzelbee** [comment]
@krobipd 
Danke für die Suche und deine Hilfe. Das sieht mir (nach einem schnellen Blick) nach der Lösung aus. Es war klar, das das Zertifikat, das ich einbauen musste irgendwann kaputt gehen würde. ;)
Ich sehe zu, dass ich das kurzfristig fixe.

**Comment by ManuW19** [comment]
Hallo, auch mit der Version 0.9.2 kommt Fehlermeldung „ (3483) getDyson2faMailError: Request failed with status code 401“ und keine Mail.

**Comment by Grizzelbee** [comment]
@ManuW19 

Der 401 ist jetzt aber ein anderes Fehlerbild. 
401 bedeutet das deine eingegeben Login Daten falsch sind. Bitte überprüfen und korrigieren.

**Comment by Phillipp83** [comment]
Hallo, Ich habe ebenfalls dieselbe Fehlermeldung 401.
Ich habe den Adapter komplett gelöscht und neu drauf gemacht und ich bin mir sicher, dass ich die Anmeldedaten richtig eingegeben habe.

**Comment by Milo-PRT** [comment]
mit v0.9.2 ist alles ok - Herzliches Dankeschön.

**Comment by ManuW19** [comment]
Anmeldedaten sind richtig!
Nach Start des Apapters kommt Fehlermeldung „ 12476) getDysonToken: Error: Request failed with status code 400“
und beim Anforderung der Mail die andere Fehlermeldung. Bekomme es nicht hin.

**Comment by Grizzelbee** [comment]
@ManuW19 
Okay. Dann der Reihe nach:
* Bitte lies und befolge die [ReadMe](https://github.com/Grizzelbee/ioBroker.dysonairpurifier) zum Adapter - speziell alles zu den Voraussetzungen und zur Installation. 
* ggf. den Adapter einfach noch einmal deinstallieren und die v0.9.2 neu installieren
* Sollte es dann immer noch nicht laufen, öffne bitte einen neuen Issue mit Angabe von:
Betriebssystem des Brokers, Versionen von js-controller, Admin, Node, dyson-Adapter, Debug-Log vom Broker komplett vom Start des Adapters bis zum Fehler, Konsolen Log des Browsers, das den Fehler im Admin anzeigt.
