### ISSUE TITLE
Bekomme keine 2FA Email

### ISSUE THREAD

**Issue by ManuW19** [Grizzelbee/ioBroker.dysonairpurifier#120]
Hallo,

Bekomme einfach keine Email. In den LOGs steht die Fehlermeldung „ getDyson2faMailError: unable to verify the first certificate“ 
Habe ein Dyson Account und benutze die neueste Version.
Kann mir jemand helfen?

**Comment by Milo-PRT** [comment]
Hallo - habe den selben Eintrag im Log:


dysonairpurifier.0 | 2021-08-10 10:19:49.142 | error | getDyson2faMailError: unable to verify the first certificate
-- | -- | -- | --
dysonairpurifier.0 | 2021-08-10 10:19:20.878 | error | [main()] error: undefined, stack: undefined
dysonairpurifier.0 | 2021-08-10 10:19:20.669 | info | Querying devices from dyson API.
dysonairpurifier.0 | 2021-08-10 10:19:20.518 | info | starting. Version 0.9.1 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v12.22.4, js-controller: 3.3.15

**Comment by HxNetwork** [comment]
Hier das gleiche Problem
`


dysonairpurifier.0 | 2021-08-16 12:27:55.346 | error | getDyson2faMailError: unable to verify the first certificate
-- | -- | -- | --
dysonairpurifier.0 | 2021-08-16 12:27:09.214 | error | [main()] error: undefined, stack: undefined

`

**Comment by Grizzelbee** [comment]
Das ist praktisch ein duplicate zu: https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/119
Die Ursache ist die Selbe. Dyson hat allem Anschein nach das Zertifikat, das ich verwende widerrufen. Update kommt ...
Nachverfolgung bitte in Issue #119 - deshalb schließe ich den hier als duplicate.
