### ISSUE TITLE
calculate filter life (filf) in % not in hours

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.dysonairpurifier#13]

**Comment by Grizzelbee** [comment]
Should be fixed in upcoming version 0.5.0

**Comment by Grizzelbee** [comment]
Issue is still acive.

**Comment by Grizzelbee** [comment]
![image](https://user-images.githubusercontent.com/5459426/97625658-14360d00-1a29-11eb-9331-f1eb7461d900.png)

**Comment by jpwenzel** [comment]
How about providing both values (hours and percentage)?
This would allow reacting on a threshold warning if the filter needs to be replaced in the next ```x```days?

**Comment by Grizzelbee** [comment]
@jpwenzel Alreday thought about it and implemented it quickly for V0.7.0

**Comment by Grizzelbee** [comment]
Fixed in version 0.7.1
