### ISSUE TITLE
PH03 Support

### ISSUE THREAD

**Issue by geogad** [Grizzelbee/ioBroker.dysonairpurifier#154]
Hi,

gleich mal vorab: cooles plugin!

Eine Frage: plant Ihr den PH03:

dysonairpurifier.0 | 2021-11-06 16:44:58.153 | warn | (9279) Please open an Issue on github if you think your device should be supported.
dysonairpurifier.0 | 2021-11-06 16:44:58.152 | warn | (9279) Device with serial number [xxxxxx] not added, hence it is not supported by this adapter. Product type: [358E]

zu supporten?

Danke!
Georg

**Comment by Grizzelbee** [comment]
Hallo Georg,

habe ich gerade in der Vesion 2.2.0 umgesetzt, die im Laufe des späteren Tages im Latest-Repo angeboten werden sollte. Bitte teste die mal. Soweit sich am PH03 keine Ändereungen gegenüber dem PH01 ergeben haben, sollte der sofort voll unterstützt werden - wenn der irgendwelche zusätzlichen Sensoren oder sonstwas hat: Mach gerne neue Feature-Requests dafür auf.
Wenn alles zu deiner Zufriedenheit funktioniert mach bitte diesen Issue zu. Das ist dann für mich das Zeichen die Version ins stable-repo zu schieben,

**Comment by geogad** [comment]
Vielen Dank! 

Works like a charm! (hatte kurz probleme die Anmeldedaten mit der alten Instanz wegzubekommen, ich denke das ist aber kein usecase).

Habe alle sensoren bzw. schreibbaren werte auf plausibilität getestet --> mir wäre nichts aufgefallen, hauptfunktionen gehen. 

Denke das ist ein Kandiat fürs stable repo.
