### ISSUE TITLE
Connection Issue

### ISSUE THREAD

**Issue by flolee** [Grizzelbee/ioBroker.dysonairpurifier#156]
Hi,

first: Thank you for your great work!

I would love to connect iobroker to my Dyson Purifier Cool Formaldehyde. It has worked before, but since two days or so i'l only get this:

```

dysonairpurifier.0
2021-11-22 23:44:34.640	info	K3G-EU-* - MQTT reconnecting.

dysonairpurifier.0
2021-11-22 23:44:33.639	info	K3G-EU-* - MQTT disconnected.

dysonairpurifier.0
2021-11-22 23:44:33.633	info	K3G-EU-* - MQTT reconnecting.

dysonairpurifier.0
2021-11-22 23:44:32.632	info	K3G-EU-* - MQTT disconnected.

dysonairpurifier.0
2021-11-22 23:44:32.628	info	K3G-EU-* - MQTT reconnecting.

dysonairpurifier.0
2021-11-22 23:44:31.627	info	K3G-EU-* - MQTT disconnected.

```

Any suggestions on how to fix this issue? I tried reinstalling the adapter, as i tried to factory reset the Dyson. 

Thank you!
All the best
Florian

**Comment by flolee** [comment]
Sorry, after days of trying i just reseted the router => now it works. 
Sorry about that!

**Comment by Grizzelbee** [comment]
@flolee 
No worries. :) 

Just for documentation and having it said - if someone else dicovers such a problem and finds this issue:
* I also had a similar problem some time ago and solved it simply by disconnecting the power plug from the dyson and waiting a minute before reconnecting it. It seems that the mqtt server inside the dyson crashes sometimes and resetting the network helps.
