### ISSUE TITLE
MQTT Verbindungsprobleme

### ISSUE THREAD

**Issue by Duggles1301** [Grizzelbee/ioBroker.dysonairpurifier#197]
Hallo, nach dem einrichten und verifizieren des Adapters hat dieser auch meinen Lüfter gefunden, kann diesen aber nicht verbinden.
Er bleibt in einer Art Schleife hängen. Das kommt im Log im Sekundentakt:

dysonairpurifier.0 | 2022-05-17 19:06:16.082 | info | NN2-EU-PBA0802A - MQTT disconnected.
dysonairpurifier.0 | 2022-05-17 19:06:16.078 | info | NN2-EU-PBA0802A - MQTT reconnecting.
dysonairpurifier.0 | 2022-05-17 19:06:15.077 | info | NN2-EU-PBA0802A - MQTT disconnected.
dysonairpurifier.0 | 2022-05-17 19:06:15.073 | info | NN2-EU-PBA0802A - MQTT reconnecting.
dysonairpurifier.0 | 2022-05-17 19:06:14.072 | info | NN2-EU-PBA0802A - MQTT disconnected.
dysonairpurifier.0 | 2022-05-17 19:06:14.067 | info | NN2-EU-PBA0802A - MQTT reconnecting.
dysonairpurifier.0 | 2022-05-17 19:06:13.066 | info | NN2-EU-PBA0802A - MQTT disconnected.
dysonairpurifier.0 | 2022-05-17 19:06:13.062 | info | NN2-EU-PBA0802A - MQTT reconnecting.
dysonairpurifier.0 | 2022-05-17 19:06:12.061 | info | NN2-EU-PBA0802A - MQTT disconnected.
dysonairpurifier.0 | 2022-05-17 19:06:12.057 | info | NN2-EU-PBA0802A - MQTT reconnecting.
dysonairpurifier.0 | 2022-05-17 19:06:11.056 | info | NN2-EU-PBA0802A - MQTT disconnected.
dysonairpurifier.0 | 2022-05-17 19:06:11.049 | info | NN2-EU-PBA0802A - MQTT reconnecting.
dysonairpurifier.0 | 2022-05-17 19:06:10.048 | info | NN2-EU-PBA0802A - MQTT disconnected.
dysonairpurifier.0 | 2022-05-17 19:06:10.043 | info | NN2-EU-PBA0802A - MQTT reconnecting.

Wäre dankbar über eine Lösung, dass ich meinen Dyson richtig nutzen kann in ioBroker

**Comment by Grizzelbee** [comment]
Ich kenne dieses Verhalten, wenn der dyson selbst nicht sauber mit dem Netz verbunden ist, oder der Router (genauer: der lokale DNS) einen Knick hat. Will sagen: Es passiert schon mal das der DNS eine falsche IP für einzelne Geräte im Cache hat. Dann hilft es in der Regel:
* den Lüfter zu resetten (10 Sec vom Strom trennen)
* den Router zu resetten (10 Sec vom Strom trennen)

Ich bin mir ziemlich sicher, das das hilft - oder Du trägst die korrrekte IP in den Objektbaum ein (siehe Doku des Adapters)

**Comment by Duggles1301** [comment]
Okay das mit der IP-Adresse eintragen hat geklappt. Nach 1x neustarten waren dann alle werte da

Vielen Dank
