### ISSUE TITLE
log wird quasi überfüllt bei dis/reconnect Probleme

### ISSUE THREAD

**Issue by krobipd** [Grizzelbee/ioBroker.dysonairpurifier#199]
hallo

vl könntest du ein limit einbauen damit das log nicht voll gespamt wird mit dis- und reconnect Meldungen.

manchmal hat mein Dyson wlan Probleme, die sich quasi nur mit einem Neustart des Gerätes beheben lassen, dann wird das log im iobroker im quasi Sekunden tagt mit diesen Meldungen voll gemacht - vl könntest du da bei 5 versuchen oder so ein limit einrichten für diese Meldungen.

dysonairpurifier.0 | 2022-08-10 17:28:40.425 | info | Starting Polltimer with a 120 seconds interval.
-- | -- | -- | --
dysonairpurifier.0 | 2022-08-10 17:28:40.424 | info | C4H-EU-NHA6440A - MQTT connection established.
dysonairpurifier.0 | 2022-08-10 17:28:39.284 | info | C4H-EU-NHA6440A - MQTT reconnecting.
dysonairpurifier.0 | 2022-08-10 17:28:38.282 | info | C4H-EU-NHA6440A - MQTT disconnected.
dysonairpurifier.0 | 2022-08-10 17:28:36.212 | info | C4H-EU-NHA6440A - MQTT reconnecting.
dysonairpurifier.0 | 2022-08-10 17:28:35.212 | info | C4H-EU-NHA6440A - MQTT disconnected.
dysonairpurifier.0 | 2022-08-10 17:28:33.141 | info | C4H-EU-NHA6440A - MQTT reconnecting.
dysonairpurifier.0 | 2022-08-10 17:28:32.139 | info | C4H-EU-NHA6440A - MQTT disconnected.
dysonairpurifier.0 | 2022-08-10 17:28:30.067 | info | C4H-EU-NHA6440A - MQTT reconnecting.
dysonairpurifier.0 | 2022-08-10 17:28:29.066 | info | C4H-EU-NHA6440A - MQTT disconnected.

**Comment by Grizzelbee** [comment]
Ist doch schon drin:
![grafik](https://user-images.githubusercontent.com/5459426/183980500-ba2c2b64-8887-4aa0-af93-5175adf55c7f.png)


Kennst Du noch die alte Werbung vom Anfang der 80er Jahre: "Hat Maggi auch schon reingetan"? 😉

**Comment by krobipd** [comment]
:-P sorry voll übersehen.
maggi kenn ich, aber die Werbung nicht :-P
