### ISSUE TITLE
2FA Anmeldung funktioniert nicht

### ISSUE THREAD

**Issue by steliop** [Grizzelbee/ioBroker.dysonairpurifier#202]
<p>Betriebssystem des ioBrokers:Linux</p><p>Versionen von js-controller:4.0.23</p><p>admin:6.2.22</p><p>Node: 16.18.0</p><p>dysonairpurifier:2.5.1</p><p>NPM 8.19.2</p><p></p><p>Die ‘A token has been received and stored’ Checkbox ist grau </p><p></p><p>Wenn ich das One-time-password eingebe und finish drücke, sehe ich im log ‘getDysonToken: Error: Request failed with status code 400’.</p><p></p><p></p><p>Log vom ioBroker</a></p><p></p><p>

dysonairpurifier.0 | 2022-10-22 17:16:03.893 | error | getDysonToken: Error: Request failed with status code 400
-- | -- | -- | --
dysonairpurifier.0 | 2022-10-22 17:15:41.380 | error | getDysonToken: Error: Request failed with status code 400
dysonairpurifier.0 | 2022-10-22 17:14:56.561 | error | [main] error: [dysonGetDevicesFromApi] Error: (undefined) Error: Request failed with status code 401, Callstack: Error: Request failed with status code 401    at createError (/opt/iobroker/node_modules/iobroker.dysonairpurifier/node_modules/axios/lib/core/createError.js:16:15)    at settle (/opt/iobroker/node_modules/iobroker.dysonairpurifier/node_modules/axios/lib/core/settle.js:17:12)    at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/iobroker.dysonairpurifier/node_modules/axios/lib/adapters/http.js:322:11)    at IncomingMessage.emit (node:events:525:35)    at IncomingMessage.emit (node:domain:489:12)    at endReadableNT (node:internal/streams/readable:1358:12)    at processTicksAndRejections (node:internal/process/task_queues:83:21), stack: undefined
dysonairpurifier.0 | 2022-10-22 17:14:56.559 | error | [main] Error while querying devices from dyson servers. The most common issue is that you haven't finished the 2FA process. Please refer to the ReadMe for instructions.
dysonairpurifier.0 | 2022-10-22 17:14:55.026 | info | Querying devices from dyson API.
dysonairpurifier.0 | 2022-10-22 17:14:54.915 | info | starting. Version 2.5.1 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v16.18.0, js-controller: 4.0.23
dysonairpurifier.0 | 2022-10-22 17:14:46.767 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
dysonairpurifier.0 | 2022-10-22 17:14:46.761 | info | terminating
dysonairpurifier.0 | 2022-10-22 17:14:46.758 | info | Cleaned up everything...
dysonairpurifier.0 | 2022-10-22 17:14:46.751 | info | Got terminate signal TERMINATE_YOURSELF

</p><p></p><p></p><p></p><p>Habe mich an die Infos im Readme gehalten und Anmeldedaten bei Dyson sind auch richtig.</p>

**Comment by Grizzelbee** [comment]
Moin @steliop 

ich kann das Problem hier bei mir leider nicht nachvollziehen. Der 2FA Prozess funktioniert nach wie vor einwandfrei.

Probiere es bitte einfach noch einmal - aber melde dich vorher aus der dyson App ab. Es ist ein bekanntes Phänomen, das das 2 FA nicht funktioniert, wenn man noch in der App eingeloggt ist.

Der Vorgang sollte so aussehen:
1. Benutzername, Pwd und Account-Land in der Config eintragen.
2. 2-FA-Email Button anklicken (Challenge-ID sollte daraufhin automatisch eingetragen werden und du bekommst eine Mail mit einem 6-stelligen Code)
3. Diesen Code in das Feld "dyson Einmalpasswort" eintragen und den Button "Finish" anklicken. Daraufhin sollte der 2-FA Prozeß abgeschlossen werden und der Adapter sich verbinden.

> Die ‘A token has been received and stored’ Checkbox ist grau 

Das soll so sein. Die Box wird nur vom Adapter geändert. Die wird angehakt sobald das Token empfangen und gespeichert wurde. Ohne token bleibt die leer. Das ist nur eine optische Hilfe, da das Token ja nicht angezeigt wird.

**Comment by steliop** [comment]
Hallo Grizzelbee,
habe mich jetzt sicher von der App abgemeldet, bekomme aber noch immer einen 401er.
ich bekomme jetzt auch keinen dyson challengeid und damit auch keine email mit dem ot-pw.
Der Zugriff auf die dyson API dürfte über ein CDN (cloudflare) gehe und der Server dort dürfte mich (bzw. meine IP) gesperrt haben.

Habe versucht den server mit 
curl -s -X POST -H "Content-Type: application/json" -k 'https://appapi.cp.dyson.com/v3/userregistration/authenticate?country=AT' -d  '{\"Email\":\"xxxx@xxx.xxx\",\"Password\":\"xxxxxxxxxxxxxx\"}'
anzusprechen und bekomme einen error code 1020.
Viele Dank für deine Hilfe.

lg stelio

**Comment by Grizzelbee** [comment]
> Der Zugriff auf die dyson API dürfte über ein CDN (cloudflare) gehe und der Server dort dürfte mich (bzw. meine IP) gesperrt haben.

Hmm. Ja - da ist CloudFlare involviert, aber ich glaube eigentlich nicht das da so schnell etwas passiert. Ich bin während der Entwicklung auch nicht gesperrt worden - und da gab es schon den einen oder anderen Fehlversuch. 😉  Und selbst wenn Du gesperrt worden bist würde ich vermuten das sich nach ein paar Tagen entweder deine IP geändert hat oder du entsperrt wurdest. Aber sind alles nur Vermutungen - ich habe da auch kein Druidenwissen.

> ich bekomme jetzt auch keinen dyson challengeid und damit auch keine email mit dem ot-pw.

Du könntest noch mal, wenn Du im IOB Admin bist, mit F12 die Dev-Konsole öffnen und gucken ob da auf der Log-Konsole etwas hilfreiches ausgegeben wird. Aber da Du ja einen 401er bekommst - kommst Du ja zum Server durch.

Im Zweifel würde ich den Adapter noch einmal komplett deinstallieren, alle Objekte, instanzen, etc löschen - neu installieren und dann noch einmal versuchen. Vielleicht hat sich im IOB etwas verklemmt.

**Comment by Grizzelbee** [comment]
Hallo @steliop 

irgendwelche Fortschrite bzgl. des Adapterters bzw. der Anmeldung?

**Comment by steliop** [comment]
Hallo Grizzelbee,
habe heute wieder versucht einen challengeid zu bekommen, habe aber immer noch einen 401'er bekommen.
Dann wollte ich mich im IOS anmelden und dort bekam ich die Meldung "das password ist ungültig".
Strange weil das PW sicher ok war. Ich konnte damit in Mydyson einlogen. Ich habe dann das PW zurückgesetzt,
Habe noch einmal versucht mit dem ioBroker reinzukommen und habe sofort einen challengid bekommen 
und nach OTP eingabe hat (fast) alles funktioniert.
Im Log sah ich dann im Sekundentakt folgende Meldung:   


dysonairpurifier.0
	2022-10-31 19:25:30.252	info	VS8-EU-NGA5955A - MQTT disconnected.
dysonairpurifier.0
	2022-10-31 19:25:30.243	info	VS8-EU-NGA5955A - MQTT reconnecting.
dysonairpurifier.0
	2022-10-31 19:25:29.243	info	VS8-EU-NGA5955A - MQTT disconnected.
dysonairpurifier.0
	2022-10-31 19:25:29.230	info	VS8-EU-NGA5955A - MQTT reconnecting.


Habe VS8-EU-NGA5955A auf meinen bind server auf dyson-pc zeigen lassen und jetzt funtioniert alles :-)
Noch einmal vielen Dank für deine Hilfe.

lg stelio

**Comment by Grizzelbee** [comment]
Schön! Freut mich, wenn es jetzt läuft. 👍 

> Habe VS8-EU-NGA5955A auf meinen bind server auf dyson-pc zeigen lassen und jetzt funtioniert alles :-)

Ja - das ist so gewollt. Der Adapter geht erst einmal davon aus (hofft) das der dyson via DNS erreichbar ist (weil er ja die IP nicht kennt). Da Fritzboxen per default einen DNS haben, funktioniert das auch oft gut. Alternativ kann das Gerät natürlich (wie in deinem Fall) in einen externen DNS aufgenommen werden, oder man träft die IP von Hand unter Hostname in den Objektbaum ein.
Beides führt zum Ziel.

> Noch einmal vielen Dank für deine Hilfe.

Sehr gerne! 👍
