### ISSUE TITLE
PT4-EU-PAA5932A - ständige MQTT-Reconnects

### ISSUE THREAD

**Issue by hatage** [Grizzelbee/ioBroker.dysonairpurifier#203]
Hallo Grizzelbee, seit ein paar Tagen kann ich mein Gerät über iobroker nicht mehr bedienen. Es sendet ständige MQTT-Reconnects.
![Bildschirmfoto 2022-11-05 um 17 16 00](https://user-images.githubusercontent.com/37780452/200129553-354ac0ca-67cc-48d4-a881-a8581e364f5f.png)

Ein anderes Gerät, der K1Y-EU-PDB5861A, funktioniert hingegen problemlos.
Ich habe den Adapter mehrfach neu gestartet und auch die 2FA-Anmeldung wiederholt, der Fehler bleibt jedoch.
Das Gerät habe ich mit dem kompletten Objektbaum gelöscht und es wurde wieder angelegt, aber unvollständig.
![Bildschirmfoto 2022-11-05 um 17 20 28](https://user-images.githubusercontent.com/37780452/200129768-e5379b2f-2795-434e-a763-f5b1cdc2fa39.png)

Was könnte der Fehler sein?

VG Hans-Ulrich

**Comment by Grizzelbee** [comment]
Hallo Hans-Ulrich,

das Proble kenne ich und habe es auch unter "known issues" mit aufgelistet (https://github.com/Grizzelbee/ioBroker.dysonairpurifier#known-issues). 
Das Problem ist normalerweise, dass der Adapter den Lüfter schlicht netzwerkseitig nicht erreichen/finden kann.
* Bei mir selbst hat es bislang immer gereicht den Lüfter selbst einmal stromlos zu machen und wieder einzuschalten. dann resettet sich seine Netzwerkverbindung und es läuft wieder.
* In einem anderen Fall war es nötig den Router zu resetten, weil der interne DNS einen Schluckauf hatte.
* Wenn Du einen eingenständigen DNS betreibst, solltest Du den mal restarten.
* Vielleicht hat der Lüfter auch einfach nur vom DHCP Server eine neue IP bekommen und du musst die aktuelle im Objektbaum unter "Hostname" eintragen.

Viele mögliche Ursachen für das selbe Problem. da ich dein Setup nicht genauer kenne musst Du mal gucken was auf deinen Fall passen kann.

**Comment by Grizzelbee** [comment]
Issue wegen Inaktivität geschlossen. Bitte erneut öffnen wenn das Problem forstbesteht.
