### ISSUE TITLE
Verbinden mit Gerät oder Dienst nicht mehr möglich

### ISSUE THREAD

**Issue by hohmannc85** [Grizzelbee/ioBroker.dysonairpurifier#204]
Adapter kann sich nicht mehr verbinden.
Cloud Daten und neuer Code wurden angefordert (Anforderung etc. funktioniert)
Adapter bleibt jedoch auf rot für Gerät und Dienst. 
Im Log ständiger MQTT reconnect

**Comment by Grizzelbee** [comment]
Mit den wenigen, ungenauen Informationen und ohne Log weiß ich ehrlich gesagt nicht wie ich hier helfen soll.
Ständiger MQTT reconnect klingt aber als könne der Adapter das Gerät nicht finden. Infos dazu gibt es unter "known Issues" im Readme - obschon es eigentlich kein issue des Adapters ist.

Wenn ich hier weiterhelfen soll, brauche ich mehr und bessere Infos.

**Comment by hohmannc85** [comment]
Moin, sorry hier nochmal etwas ausführlicher:
Ich habe einen Dyson Pure Humidify+Cool, der hatte bislang auch wunderbar mit dem Adapter funktioniert, ich kann daher leider nicht sagen, seit wann es nicht mehr geht. Daten zum login habe ich eingetragen. Der challengeld wird abgefragt, 2FA funktioniert auch. Der Adapter bleibt jedoch inaktiv. Im Log steht:


dysonairpurifier.0 | 2022-11-13 21:18:04.278 | info | C4J-EU-NKA1477A - MQTT reconnecting.
-- | -- | -- | --
dysonairpurifier.0 | 2022-11-13 21:18:03.277 | info | C4J-EU-NKA1477A - MQTT disconnected.
dysonairpurifier.0 | 2022-11-13 21:18:03.270 | info | C4J-EU-NKA1477A - MQTT reconnecting.
dysonairpurifier.0 | 2022-11-13 21:18:02.269 | info | C4J-EU-NKA1477A - MQTT disconnected.
dysonairpurifier.0 | 2022-11-13 21:18:02.215 | info | C4J-EU-NKA1477A - MQTT reconnecting.
dysonairpurifier.0 | 2022-11-13 21:18:01.214 | info | C4J-EU-NKA1477A - MQTT disconnected.
dysonairpurifier.0 | 2022-11-13 21:18:01.212 | info | C4J-EU-NKA1477A - MQTT offline.
dysonairpurifier.0 | 2022-11-13 21:18:01.194 | info | C4J-EU-NKA1477A - MQTT connection requested for [C4J-EU-NKA1477A].
dysonairpurifier.0 | 2022-11-13 21:18:01.117 | info | Trying to connect to device [C4J-EU-NKA1477A] via MQTT on host address [C4J-EU-NKA1477A].
dysonairpurifier.0 | 2022-11-13 21:18:01.115 | info | No host address given. Trying to connect to the device with it's default hostname [C4J-EU-NKA1477A]. This should work if you haven't changed it and if you're running a DNS.
dysonairpurifier.0 | 2022-11-13 21:18:00.775 | info | Querying devices from dyson API.
dysonairpurifier.0 | 2022-11-13 21:18:00.687 | info | starting. Version 2.5.1 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v16.18.0, js-controller: 4.0.23


Über die App habe ich zugriff. Der Wlan empfang ist sehr gut!.

**Comment by Grizzelbee** [comment]
Wie ich bereits schrieb:
> Ständiger MQTT reconnect klingt aber als könne der Adapter das Gerät nicht finden. Infos dazu gibt es unter "known Issues" im Readme - obschon es eigentlich kein issue des Adapters ist.

Die IP deines Ventilators wird allem Anschein nach vom DNS Server (in deinem Router integriert (FritzBox) oder dediziert) nicht richtig aufgelöst. Das ist kein Problem des Adapters, sondern eins in deinem Netzwerk. Das kann schon mal passieren.
Bitte einfach erst einmal den Ventilator resetten (ausstecken, kurz warten und wieder einstecken). Sollte das nicht helfen das Selbe mit dem Router (und ggf dem Server) machen - je nachdem wo dein DNS Server läuft.
Alternativ kannst Du auch die IP deines Ventialtors fest im Adapter eintragen.

**Comment by hohmannc85** [comment]
habe die ip eingetragen, jetzt gehts! danke:)

**Comment by suxus-zz** [comment]
Hallo
Ich habe bei mir auch dieses "disconnected" und "reconnected" meine Vermutung ist, da die ioBroker Instanz in meinem normal 192.168.9.x Netz läuft und meine beiden Dyson Geräte im IOT Netz sind 192.168.5.x findet er diese nicht. Ich wollte nun versuchen die IP der Geräte auch fix zu erfassen aber ich weiss nicht wo, kann da jemand helfen?
Vielen herzlichen Dank

**Comment by suxus-zz** [comment]
Habe es gerade selber gefunden, man muss unter OBJEKTE und dann beim entsprechenden Dyson-Objekt unter Hostaddress (in der Spalte WERT) klicken und dann kann man die IP eintragen. Anschliessend Instanz neu starten.

Mein Fehler war ich habe nicht in die Wert-Spalte geklickt, sondern immer den Stift geklickt und dachte ich muss da was rein schreiben!
