### ISSUE TITLE
falsche Datentyp Warnung - SystemState.product-warnings.FILTER_REPLACEMENT

### ISSUE THREAD

**Issue by krobipd** [Grizzelbee/ioBroker.dysonairpurifier#213]
hallo mit der aktuellen 2.5.4 kommt momentan diese Warnung

State value to set for "dysonairpurifier.0.xxxxx.SystemState.product-warnings.FILTER_REPLACEMENT" has to be type "boolean" but received type "string"

**Comment by Grizzelbee** [comment]
Das kann ich so leider nicht nachvollziehen. In meiner Umgebung passiert das nicht.
Schreib doch bitte mal ein debug-log und filter das auf FILTER_REPLACEMENT.
Ich erwarte das dann einmal die Warnung kommt und zum anderen die Meldung:
```
FILTER_REPLACEMENT is a bool switch. Current state: [OK] --> returnvalue for further processing: false
```
Alternativ könnte auch folgendes kommen:
```
FILTER_REPLACEMENT is a bool switch. Current state: [Fail] --> returnvalue for further processing: true
```

Poste das bitte mal hier und dann noch js-controller Version und NodeJs Version.
Dann sehen wir weiter.

**Comment by Grizzelbee** [comment]
Vergiss es. Ich habe das Problem gefunden.
Fix kommt...
