### ISSUE TITLE
Cannot parse json data when special chars are contained in password

### ISSUE THREAD

**Issue by mxgross** [Grizzelbee/ioBroker.dysonairpurifier#259]
Hi
thanks for your work!

I have to change my Dyson password because it contains special chars that cannot be parsed by your adapter.
Here an example what special chars may be contained an problematic:
`console.ts:40 Cannot parse json data: { "email": "mymail@xyz.com", "password": "<MyPwContains|;,^=">" , "country": "DE", "locale": "undefined"}`

Thanks

**Comment by Grizzelbee** [comment]
Hi mxGross

thanks for opening this issue.

Lets take some deeper looks:
* At what point of the adapter startup/2FA process did you notice the issue?
* How did you figured out that these special chars are responsibile for the issue?
* Have you testest other adapters with similar passwords and are they working as expected?
* Is it possible to write a (debug) logfile showing any misbehavior of the adapter?

**Comment by mxgross** [comment]
Hi @Grizzelbee 
I saw this error in the Chrome Webdeveloper Console after I could not manage to login with my Dyson credentials with multiple tries.
Then I realized that it might be due to any of the above mentioned special characters.
After changing my Dyson password to a new onem without the above special chars, it worked.

So I am no exactly sure what special char(s) cause these problems. I think you or ioBroker must escape the password chars. Maybe it was the double quote (") char, because it would end the JSON value if not escaped.

**Comment by Grizzelbee** [comment]
Okay - thanks for this infomation.

From my point of view it's a general ioBroker-Admin issue. 

My adapter uses jsonConfig (which is only a config file in json format) and fully relies on the underlying code of iobroker.admin. Since it's no good idea that every adapter that uses jsonConfig tests for these chars itself - iobroker.admin should do this work.

So please open a similar issue there. If apollon77, mcu77 or bluefox points back to the adapter developers we have a new situation to discuss.

**Comment by mxgross** [comment]
New ioBroker issue created: [https://github.com/ioBroker/ioBroker/issues/520](https://github.com/ioBroker/ioBroker/issues/520)

**Comment by mcm1957** [comment]
Storing passwords with special charactes seem to work normally.
BUT jsonConfig of the tysonairpurifier uses

``` "jsonData": "{ \"email\": \"${data.email}\", \"password\": \"${data.Password}\" , \"country\": \"${data.country}\", \"locale\": \"${data.locale}\"}",```

So this construct does not work i.e. with " inside a password.
