### ISSUE TITLE
Outdated certificate

### ISSUE THREAD

**Issue by Arcticon** [Grizzelbee/ioBroker.dysonairpurifier#274]
das zertifikat unter `certificates/intermediate.pem` ist bereits abgelaufen.
wenn man die root zertifikate von node (mozilla) nimmt, dann funktionieren die requests auch.

```
const tls = require('tls');
const httpsAgent = new https.Agent({
  ca: [...tls.rootCertificates],
  rejectUnauthorized: false
});
```

**Comment by Grizzelbee** [comment]
Welche Requests genau fahren denn gegen die Wand? 😲 
Mir ist da nichts bekannt.

**Comment by Arcticon** [comment]
noch funktioniert alles. es kann sein, dass es in zukunft nicht mehr funktioniert.
und je weniger dependencies, desto besser :)
