### ISSUE TITLE
Values ​​are not sent to Dyson devices v3.1.8 / Werte werden nicht zu Dyson Geräte übermittelt V3.1.8

### ISSUE THREAD

**Issue by sansonifabio** [Grizzelbee/ioBroker.dysonairpurifier#278]
Hello @Grizzelbee,

Since version 3.1.8, no values ​​such as on/off are transferred to the Dyson.
If I install version 3.1.7 again it will work again, can you please check itb. There's nothing in the log.

Operating system: Linux Debian Bookworm
Node.js: v18.20.2
NPM: 10.5.0
Path: /opt/iobroker/

Best regards
Fabio
------------------------------------------------------------------------------------------------------------------------------------

Hallo @Grizzelbee, 

seit der Version 3.1.8 werden keine Werte zum Beispiel An / Aus an die Dyson Geräte übertragen. 
Wenn ich wieder die Version 3.1.7 installiere geht  es wieder, kannst du das mal bitte prüfen. Im Log steht nix.

Betriebssystem: Linux Debian Bookworm
Node.js: v18.20.2
NPM: 10.5.0
JS: 5.0.19
Pfad: /opt/iobroker/

Liebe Grüße
Fabio

**Comment by Grizzelbee** [comment]
Hi Fabio,

can corfirm this Bug - and have currently no idea what might have happened to the code.
Therefore I need some time for research.

best Hanjo

------------------------

Hi Fabio,

ich kann den Bug bestätigen - und habe gerade keine Idee was da passiert sein könnte.
Brauche etwas Zeit zum Suchen.

liebe Grüße
Hanjo

**Comment by sansonifabio** [comment]
@Grizzelbee everything's fine, take your time, do it in peace. Possibly this (grizzelbee) Chg: code refactoring (arcticon) Chg: code refactoring?

Kind regards
Fabio




@Grizzelbee alles gut, lass dir Zeit mach es in Ruhe. 
Evtl. das (grizzelbee) Chg: code refactoring (arcticon) Chg: code refactoring?

Liebe Güße 
Fabio

**Comment by Arcticon** [comment]
ich konnte das problem identifizieren und loesen.
das problem ist folgendes: In der UI setzen wir einen wert, nehmen wir an `MainPower`. dieser kommt als action in `onStateChange`. hier wird dann mit `MainPower` in der `datapoints` map gesucht und nichts gefunden.
auf der anderen seite sendet der mqtt client den wert `fpwr`, welcher in der `datapoints` map enthalten ist.

ich habe dazu eine `nameToDysoncode` translation geschrieben.

**Comment by Arcticon** [comment]
@Grizzelbee erstellst du eine neue version mit dem fix? :)

**Comment by Grizzelbee** [comment]
Yapp. Habe sie gerade getestet und für mich sieht das gut aus. 
Danke!
