### ISSUE TITLE
seit 3.1.8 - State value to set for "dysonairpurifier.0.xxxx.Sleeptimer" has to be type "string" but received type "number"

### ISSUE THREAD

**Issue by krobipd** [Grizzelbee/ioBroker.dysonairpurifier#281]
Seit Version 3.1.8 gibt in meinen log ständig diese Fehlermeldung, betrifft scheinbar nur den humidify+cool

bei meinem pure cool gibs den Fehler nicht und der datenpunkt hat auch den richtigen wert.

beim humidify+cool steht null im wert

**Comment by Arcticon** [comment]
@krobipd kannst du das bitte mal mit 3.1.9 testen?

**Comment by krobipd** [comment]
SerwusJa auch mit 3.1.9 :-/Von meinem iPhone gesendetAm 14.05.2024 um 09:04 schrieb Maximilian Kramp ***@***.***>:﻿
@krobipd kannst du das bitte mal mit 3.1.9 testen?

**Comment by Grizzelbee** [comment]
Habe das Problem gefunden und kümmere mich um eine Lösung...

**Comment by krobipd** [comment]
Vielen Dank 🙏 Von meinem iPhone gesendetAm 14.05.2024 um 10:47 schrieb Grizzelbee ***@***.***>:﻿
Habe das Problem gefunden und kümmere mich um eine Lösung...

**Comment by Arcticon** [comment]
@Grizzelbee sieht aus als wenn `sltm` `type: 'string'` haben sollte, richtig?

**Comment by Grizzelbee** [comment]
V3.1.10 fixed das.

**Comment by Grizzelbee** [comment]
@Arcticon 
> sieht aus als wenn sltm type: 'string' haben sollte, richtig?

Nein - Number ist richtig. Das sind die (rest) Minuten, die der Timer noch läuft.
