### ISSUE TITLE
Version 3.1.10 is not currently available for ioBroker / Version 3.1.10 wird im ioBroker nicht angeboten

### ISSUE THREAD

**Issue by sansonifabio** [Grizzelbee/ioBroker.dysonairpurifier#285]
Hello @Grizzelbee,

I don't see the new version 3.1.10 in ioBroker, I had to install it via Github. Normally this is always shown to me under Beta (latest).

Best regards
Fabio
---------------------------------------------------------------------------------------------------------------------------------------------
Hallo @Grizzelbee,

die neue Version 3.1.10 wird mir im ioBroker nicht angezeigt, musste sie über Github installieren. Normalerweise wird mir das immer unter Beta (latest) angezeigt.

Herzliche Grüße
Fabio

**Comment by Grizzelbee** [comment]
V3.1.10 will arrive by this day - kept version open due to ongoing changes.
Since the changes seem okay I published npm version at 08:01 (3 mins after this issue 😉 )  this morning.
