### ISSUE TITLE
Switzerland missing (again?) in country codes

### ISSUE THREAD

**Issue by hb9tvk** [Grizzelbee/ioBroker.dysonairpurifier#287]
Hi,

despite having been fixed earlier (#114 ), I don't see Switzerland in the selection for the country code.

When using 'Germany', I can start the 2FA process and am receiving the email with the code. However the 'Challenge-Id' is not filled in, and after entering the OTP, authentication still fails with 401.

From the source (index_m.html) I see that Switzerland should be after 'China', but in the Admin UI it is missing.

Tried with different browsers and uninstall/re-install the adapter with no success.

![dyson](https://github.com/Grizzelbee/ioBroker.dysonairpurifier/assets/13141458/af01086c-d759-4105-ad84-b83958f2eb79)

**Comment by Grizzelbee** [comment]
Got lost during port to jsonConfig - going to fix it.

**Comment by Grizzelbee** [comment]
please test current version from github if it works for you.

**Comment by hb9tvk** [comment]
Thanks, Switzerland is back in the Country Code list and I could successfully connect to the devices. Thanks a lot!
