### ISSUE TITLE
Device with serial number [blabla] not added, hence it is not supported by this adapter. Product type: [664]

### ISSUE THREAD

**Issue by matty67** [Grizzelbee/ioBroker.dysonairpurifier#289]
I have the new BP03. Is it possible, to add it to the adapter?

I get these message in iobroker log:
Please open an Issue on github if you think your device should be supported.
Device with serial number [blabla] not added, hence it is not supported by this adapter. Product type: [664]

**Comment by Grizzelbee** [comment]
Adding Big&Quiet devices with the (soon) upcomming version

**Comment by Grizzelbee** [comment]
please test current version from github if it works for you - including all expected functions.

**Comment by matty67** [comment]
Great. Yes it works for me. Thx.
