### ISSUE TITLE
Adapter wird nicht als Instanz angezeigt?

### ISSUE THREAD

**Issue by Day1983** [Grizzelbee/ioBroker.dysonairpurifier#43]
HAllo, ich habe über die URL den Adapter mit der V 0.7. installiert - leider taucht der Adapter nicht unter den INSTANZEN auf.

Unter Adapter taucht der Dyson auf mit der Vers. 0.7. (installiert)

**Comment by Grizzelbee** [comment]
Das ist vollkommen normal. Nicht jeder vorhande Adapter soll ja auch eine Instanz erzeugen. Deshalb musst du beim Adapter erst auf das drei-Punkte-Menü und dann auf das kleine Plus links unten klicken. Dann erst wird eine Instanz erzeugt. Wenn der Adapter erst einmal im Repo ist, ist das ja auch genau der Weg über den Du dann eine Instanz erzeugen würdest.
