### ISSUE TITLE
Unable to set United Kingdom as country

### ISSUE THREAD

**Issue by jmslln** [Grizzelbee/ioBroker.dysonairpurifier#48]
Hello! 

Thanks for writing this adapter - having just bought a TP04 I thought I would install it on my Pi running iobroker.

All goes well until I set the Country to United Kingdom:  when I save and close  then reopen the settings the country has changed to United States.  Do you have any advice for where I can start to look for solutions?

Many thanks
James

**Comment by jmslln** [comment]
Here are some lines from the log:


dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | at async dysonAirPurifier.main (/opt/iobroker/node_modules/iobroker.dysonairpurifier/main.js:692:13)
-- | -- | -- | --
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | at processTicksAndRejections (internal/process/task_queues.js:93:5)
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | at /opt/iobroker/node_modules/iobroker.dysonairpurifier/main.js:724:63
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | at JSON.stringify (<anonymous>)
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | --- property 'socket' closes the circle
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | \| property '_httpMessage' -> object with constructor 'ClientRequest'
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | --> starting at object with constructor 'TLSSocket'
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | --- property 'socket' closes the circle, stack: TypeError: Converting circular structure to JSON
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | \| property '_httpMessage' -> object with constructor 'ClientRequest'
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | --> starting at object with constructor 'TLSSocket'
dysonairpurifier.0 | 2021-01-23 10:11:36.286 | error | (11254) [main()] error: Converting circular structure to JSON
dysonairpurifier.0 | 2021-01-23 10:11:36.278 | error | (11254) [error.response.headers]: [{"date":"1","content-type":"2","content-length":"3","connection":"4","cache-control":"5","pragma":"6","expires":"7","x-content-type-options":"8","x-dyson-correlatio
dysonairpurifier.0 | 2021-01-23 10:11:36.278 | error | (11254) [error.response.status]: 400
dysonairpurifier.0 | 2021-01-23 10:11:36.277 | error | (11254) [error.response.data]: [["1"],{"field":"2","error":"3"},"country","INVALID_COUNTRY"]
dysonairpurifier.0 | 2021-01-23 10:11:36.275 | error | at processTicksAndRejections (internal/process/task_queues.js:80:21)
dysonairpurifier.0 | 2021-01-23 10:11:36.275 | error | at endReadableNT (internal/streams/readable.js:1327:12)
dysonairpurifier.0 | 2021-01-23 10:11:36.275 | error | at IncomingMessage.emit (events.js:327:22)
dysonairpurifier.0 | 2021-01-23 10:11:36.275 | error | at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
dysonairpurifier.0 | 2021-01-23 10:11:36.275 | error | at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
dysonairpurifier.0 | 2021-01-23 10:11:36.275 | error | at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
dysonairpurifier.0 | 2021-01-23 10:11:36.275 | error | (11254) Error during dyson API login:Error: Request failed with status code 400, Callstack: Error: Request failed with status code 400
dysonairpurifier.0 | 2021-01-23 10:11:35.690 | info | (11254) starting. Version 0.7.0 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v14.15.4, js-controller: 3.1.6

**Comment by Grizzelbee** [comment]
Hi James!

may you please give version/branch 0.7.1 a try?
I tried to fix the problem there.

best
grizzelbee

**Comment by jmslln** [comment]
Will do -  many thanks for your reply.  Much appreciated.

If you would like me to assist in the project at all -  by testing not coding ☺  -  let me know.


James

**Comment by jmslln** [comment]
My apologies,  but please can you confirm the install url  for iobroker? https://github.com/Grizzelbee/ioBroker.dysonairpurifier/tree/Dev_0.7.1  did not work for me and I am not expert in Github  ☺

James

**Comment by Grizzelbee** [comment]
Hi James,

yes - expected this to work. Obvisiously it's not.
So please try to replace your local [...]/node_modules/iobroker.dysonairpurifier/admin/index_m.html file by the one from the 0.7.1 branch. If done you'll need to refresh the adapter in iobroker by going to the Adapters-Tab, klick on the tree-dots menu in the dyson AirPurifier tile and klick the up-arrow. It should look like some kind of update installation. After it has finished you should be able to login with the adapter.

If this doesn't work - I'll need to prepare an intermediate 0.7.1 version, upload it and then you'll definately be able to test it.

**Comment by jmslln** [comment]
Thanks for your email.

I have replaced the index_m.html  file with the edited version as you suggested.  I just had to enable expert mode to see the upload arrow.

With UK  I get the “invalid country code” error still.   With UK in there, it looks like that gets passed through to Dyson’s website which then denies the login because of the “incorrect” code.  But with GB instead of UK it seems to work ok.

So the log looks good now  although I do see a number of  (25866) Skipped creating unknown data field for: info messages  (for example Skipped creating unknown data field for: [time] Value: |-> 2021-01-25T20:43:04.000Z), but I think that is a separate issue.

Many thanks

James

**Comment by Grizzelbee** [comment]
Hi James,

thanks for figuring that UK/GB thing out. I'll fix it in the official 0.7.1 release. I really appreciate that.

These many "Skipping unknown ..." info entries in the log are currently intended and no really issue - but just an information.
dyson really has many of these four letter codes with an undocumented meaning. Some of them have already been figured out - some not. The known ones are created as data fields - the unknown are logged. Maybe someone recognizes what they are for and informs me about. But they won't stay eternally. ;o) Currently I'm decompiling and reverse engeneering the dyson android app to get more information - with some but no big success.

**Comment by jmslln** [comment]
Good stuff!  Thanks for sharing it with us – let me know if you need beta testing etc.

All the best,

James

**Comment by Grizzelbee** [comment]
Fixed in version 0.7.1

**Comment by jmslln** [comment]
Thank you!   It now lets me set Great Britain,  but when I go back to check, it says Germany in the field -  although I can see in the logs that it is still using GB  for the country code.  It seems the drop down list is not using the current country selection for its display.

James

**Comment by Grizzelbee** [comment]
New bug, introduced in 0.7.1, is fixed in new Verison 0.7.3

**Comment by jmslln** [comment]
Hello!

The “Germany” issue I reported is fixed in your latest release,  but I’m not sure this latest release works with the GB country code.  Please see the lines from my log file below (I confirm the password is correct and is the same as I use in the App on my phone):

dysonairpurifier.0
2021-02-11 07:36:58.489
error
(27965) [main()] error: undefined, stack: undefined
dysonairpurifier.0
2021-02-11 07:36:58.488
error
(27965) Credentials used for login: User:[james@jefl.co.uk] - Password:[************] - Country:[gb]
dysonairpurifier.0
2021-02-11 07:36:58.487
error
(27965) Error: Unable to authenticate user! Your credentials are invalid. Please double check and fix them.
dysonairpurifier.0
2021-02-11 07:36:58.486
error
(27965) Error during dyson API login:Error: Request failed with status code 401, Callstack: Error: Request failed with status code 401 at createError (/opt/iobroker/node_modules/axios/lib/core/cre
dysonairpurifier.0
2021-02-11 07:36:57.604
info
(27965) starting. Version 0.7.4 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v14.15.4, js-controller: 3.1.6
dysonairpurifier.0
2021-02-11 07:36:52.727
info
(24557) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
dysonairpurifier.0
2021-02-11 07:36:52.726
info
(24557) terminating
dysonairpurifier.0
2021-02-11 07:36:52.725
info
(24557) Cleaned up everything...
dysonairpurifier.0
2021-02-11 07:36:52.722
info
(24557) Got terminate signal TERMINATE_YOURSELF


Is it possible to include two country codes in the list  (GB and UK)  in a test release so I can try each and report back to you?  ( or maybe I can edit a file like I did before and add an extra country?)

All the best,

James

**Comment by Grizzelbee** [comment]
Hi James,
this 401 error is an issue all users with all versions of the adapter are faceing since yesterday afternoon.
Currently I don't know what happend and what's going on. Maybe the adapter has been banned by dyson - even I expect another error code then.
I'm trying to find a solution but can't promise anything.

**Comment by jmslln** [comment]
Ah -ok.  Thanks for the update.  Good luck!
James

**Comment by Grizzelbee** [comment]
Solved by https://github.com/Grizzelbee/ioBroker.dysonairpurifier/pull/66. 
Adapter logs in again.

**Comment by jmslln** [comment]
Thanks -  looking good here!

James
