### ISSUE TITLE
Stufenwerte für Datenpunkt VOCIndex anpassen

### ISSUE THREAD

**Issue by Day1983** [Grizzelbee/ioBroker.dysonairpurifier#52]
HAllo,

kannst Du Dir bitte mal den Datenpunkt VOCansehen?
Der Datenpunkt VOCindex sagt bei mir "verybad(3)" - mit der 3 ist er ja eigentlich "Good", aber der Datenpunkt "VOC" sagt als Zahl "11"...

Screensot anbei
![image](https://user-images.githubusercontent.com/77491820/106199740-3c631280-61b6-11eb-9fd2-f56df2e50859.png)

**Comment by Grizzelbee** [comment]
Hallo Day,
das hat alles schon so seine Richtigkeit - zumindest im Wesentlichen. 

Aber der Reihe nach:
die (3) bei Very Bad bezieht sich nicht auf den Wert der zu dieser Einstufung geführt hat, sondern ist die numerische Repräsentation von very Bad in der Liste der verschiedenen States ( 'states' : {0:'Good', 1:'Medium', 2:'Bad', 3:'very Bad', 4:'extremely Bad', 5:'worrying'}). Weil sich "3" aber so unintuitiv liest, übersetze ich das in seine Text-Repräsentation.

Der Wert, der zu dieser Einstufung geführt hat ist VOC=11.

Die Stufen sehen so aus: ( name: 'VOC QualityIndex. 0-3: Good, 4-6: Medium, 7-8, Bad, >9: very Bad', ) und sind der dyson-App entnommen.
Der Haken ist nur: Die Werte, die die Geräte raushauen gehen bis 99!
![grafik](https://user-images.githubusercontent.com/5459426/106272126-d49ddd80-6230-11eb-89ed-1e118797b92a.png)

Deshalb habe ich die Daten eine Weile mitschreiben lassen um dann genau die hier gezeigte Auswertung darüber machen zu können,  anhand derer ich dann das Verhalten im Adapter anpassen kann.

**Comment by Grizzelbee** [comment]
Richtige Stufen:
when val<40                       then good,        
when val>=40 AND val<70 then medium,        
when val>=70 AND val<90 then bad,        
when val>=90                     then very_bad

**Comment by Day1983** [comment]
Okay, merci.... 

hab noch eine Frage - Problem... neues ISSUES

**Comment by Grizzelbee** [comment]
Fixed in version 0.7.1
