### ISSUE TITLE
Unknow Data field -  auszug aus LOG File

### ISSUE THREAD

**Issue by Day1983** [Grizzelbee/ioBroker.dysonairpurifier#53]
Hallo,

erstmal riesen Kompliment für den Adapter - das ist wirklich super von Dir!

Seit gestern (oder auch 2 Tagen) bekomme ich in der LOG diese Fehlermeldungen (infos)...

![image](https://user-images.githubusercontent.com/77491820/106317218-45afb600-626e-11eb-89bf-e1f410f66d87.png)

**Comment by Grizzelbee** [comment]
HI!

Danke für das Kompliment! :)

Zu den Logeinträgen: 
dyson verwendet eine Unmenge dieser 4-Buchstaben Codes. Davon sind einge entschlüsselt - und einige eben nicht - und wiederum andere spenden keinen Nutzen für den Adapter.
Die, die ich glaube entschlüsselt zu haben - sind dem Adapter bekannt und werden als Datenpunkte angelegt. Die Unbekannten oder Nutzlosen werden aktuell noch als Info geloggt - in der Hoffnung das irgendjemand sie vielleicht entschlüsselt und mir das auch mitteilt. dann würde ich die noch einbauen. Sollten sie weiterhin unentschlüsselt bleiben, werden sie irgendwann aus dem Log verschwinden.
Im Augenblick versuche ich noch der Android-App ein paar Informationen durch decompilieren und reverse engeneering zu entlocken. Mal sehen wie weit das führt.

Die Einträge sind aber ganz klar gewollt und kein Bug des Adapters!
