### ISSUE TITLE
Startet nicht - aktueller git

### ISSUE THREAD

**Issue by krobipd** [Grizzelbee/ioBroker.dysonairpurifier#65]
Der aktuelle git, stand 10.2 23 Uhr, funktioniert bei mir nicht mehr.

meine Zugangsdaten stimmen, mein Passwort hat Sonderzeichen.

hier die Fehlermeldungen

`2021-02-10 22:51:25.565 - error: dysonairpurifier.0 (1768) Error during dyson API login:Error: Request failed with status code 401, Callstack: Error: Request failed with status code 401

at createError (/opt/iobroker/node_modules/axios/lib/core/createError.js:16:15)
at settle (/opt/iobroker/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/opt/iobroker/node_modules/axios/lib/adapters/http.js:260:11)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (internal/streams/readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-02-10 22:51:25.566 - error: dysonairpurifier.0 (1768) Error: Unable to authenticate user! Your credentials are invalid. Please double check and fix them. This adapter has a maximum Pwd length of 32 chars.
2021-02-10 22:51:25.569 - error: dysonairpurifier.0 (1768) [main()] error: Converting circular structure to JSON
--> starting at object with constructor 'TLSSocket'
\| property '_httpMessage' -> object with constructor 'ClientRequest'
--- property 'socket' closes the circle, stack: TypeError: Converting circular structure to JSON
--> starting at object with constructor 'TLSSocket'
\| property '_httpMessage' -> object with constructor 'ClientRequest'
--- property 'socket' closes the circle
at JSON.stringify ()
at /opt/iobroker/node_modules/iobroker.dysonairpurifier/main.js:724:63
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async dysonAirPurifier.main (/opt/iobroker/node_modules/iobroker.dysonairpurifier/main.js:692:13)
2021-02-10 22:51:58.598 - info: host.krobis-iotvm iobroker url`

**Comment by Grizzelbee** [comment]
Ja - das ist aktuell leider so. 

Und es liegt nicht am Adapter. Alle Versionen (auch alte) sind gleichermaßen betroffen. 
Ich vermute das dyson etwas gegen unsere Aktivitäten und uns ausgesperrt hat. Der Errorcode ist zwar ungewöhnlich dafür, aber möglich ist es dennoch. Vielleicht haben die aber auch gerade nur irgendwelche Probleme auf deren Seite. 
Wir müssen warten.

**Comment by viper4gh** [comment]
Andere API Tools haben die gleichen Probleme.
Hier hat einer einen möglichen Lösungsweg aufgezeigt:
https://github.com/etheralm/libpurecool/issues/37#issuecomment-777949022

**Comment by viper4gh** [comment]
curl -X GET -k 'https://appapi.cp.dyson.com/v1/userregistration/userstatus?country=GB&email=xyz@xyz.xy'
curl -X POST -H "Content-Type: application/json" -k 'https://appapi.cp.dyson.com/v1/userregistration/authenticate?country=DE' -d '{"Email": "xyz@xyz.xy", "Password": "PASSWORD"}'

Das hat bei mir funktioniert, allerdings habe ich vorher nicht probiert es ohne das GET aufzurufen.
D.h. ich weiß jetzt gerade nicht, ob es vielleicht nur aktuell wieder funktioniert.

**Comment by viper4gh** [comment]
Ich konnte jetzt auch den Adapter Version 0.7.3 ohne Probleme wieder starten.

**Comment by Grizzelbee** [comment]
@viper4gh 
Vielen Dank für deine Recherchen!
Die Lösung bei LibPureCool funktioniert und war schnell umgesetzt. Ohne die funktionert ein Login aber nur unter besonderen Bedingungen. :+1: 

Update kommt !!! ...

**Comment by viper4gh** [comment]
Danke fürs schnelle fixen.

Ich hab mal erst mal auf die 0.7.4 aktualisiert.
Es funktioniert noch alles, aber das Info Licht bei den Instanzen bleibt auf gelb und wenn ich mit der Maus drüber gehe
steht "Verbunden mit dysonairpurifier" auf "falsch".
Ich bekomme aber weiterhin aktuelle Daten, das kann also eigentlich nicht stimmen.

**Comment by krobipd** [comment]
vielen dank für eure tolle Arbeit :-)

ich habe aber leider noch immer das Problem das der login nicht mehr funktioniert.
ich hab gerade mit der Dyson app meine login Daten nochmal getestet und sie sind korrekt.

es ist eben ein generiertes Passwort mit Sonderzeichen wie zB "]" oder "=" drin. könnte das Probleme machen?
vor dem update hatte der Adapter sich immer korrekt eingeloggt, habe jetzt den aktuellen dev git installiert - hab einfach angenommen laut changelog das dieser das aktuellen Problem behebt.

**Comment by krobipd** [comment]
ich würde das ganze noch nicht ganz als erledigt sehen.

hatte gerade folgendes Problem.

habe den Adapter neugestartet und wieder die Fehlermeldung mit der Authentifizierung bekommen. 
habe mich dann in der Handy app ausgeloggt und neu angemeldet und dann den Adapter neu gestartet dann ging wieder alles.

**Comment by jpwenzel** [comment]
Installed the latest version from `master` this morning and confirm that login to Dyson API works for me. Thanks, @Grizzelbee!
