### ISSUE TITLE
werte werden doppelt geschrieben

### ISSUE THREAD

**Issue by krobipd** [Grizzelbee/ioBroker.dysonairpurifier#67]
hallo und erstmal vielen dank für deinen tollen adapter und deine tolle Arbeit.

verwende die aktuelle version 0.7.5
und habe einen Dyson Pure Humidify+Cool

mir ist aufgefallen das in der aktuellen version die werte doppelt geschrieben werden, also bei der Lüftergeschwindigkeit steht "0040,0040" 

die ist zB bei fanstatus, AutoHumidificationTarget, AutomaticMode, Carbonfilter, CleanDurationRemaining, ContinuousMonitoring uvm der fall.
<img width="461" alt="Bildschirmfoto 2021-02-15 um 16 49 50" src="https://user-images.githubusercontent.com/27220902/107967782-d9db8600-6fad-11eb-8922-84c76fc0da09.png">

**Comment by Grizzelbee** [comment]
Hmmm. Das kann ich so nicht nachvollziehen. Vielleicht den Adapter oder sogar den ganzen Broker mal neu starten ...

Das Einzige was ich in dem Zusammenhang kenne ist das bei der Lüftergeschwindigkeit:
![grafik](https://user-images.githubusercontent.com/5459426/108033931-0ab2ce00-7035-11eb-876c-df3d214a03ec.png)

Das kommt such die Vorgabe der möglichen Werte und ist so gewollt. Das was Du da beschreibst klingt aber anders.
Da dein Screenshot eher wie ein Log aussieht: Kannst du vielleicht einen Screenshot von deinem Objektbaum posten?

**Comment by krobipd** [comment]
das ist mir nur aufgefallen da ich Fehlermeldungen von yahka in meinem log habe die genau das selbe problem darstellen.

den Objektbaum poste ich in dem anderen thread - den feedback zu meinem gerät thread

der screenshot stammt aus dem history adapter, hier nochmal die Fehlermeldung von yahka

> (1053) [Luftbefeuchter.RotationSpeed] error while setting value AUTO,AUTO - message: Error: characteristic value expected float and received object

**Comment by Grizzelbee** [comment]
> expected float and received object

Und ich fürchte, da haben wir dann auch sofort den Missetäter. ;) 
Die Datenpunkte von dyson sind am Ende alles Strings. Bei der Lüftergeschwindigkeit wird das schön deutlich. "0001" - "0010" und "AUTO". Deswegen bemühe ich ja auch diese Übersetzungs-Sates. Wenn der History-Adapter da nun eine Zahl erwartet, muss er ja vor die Wand fahren. 
Bedeutet das, das im Objektbaum des Adapters alles okay ist? Oder geht da auch etwas quer?

**Comment by krobipd** [comment]
nach deinem tipp im anderen thread habe ich den ganzen baum neu aufgebaut und jetzt nachgesehen ob sich hier an dieser front irgendwas geändert hat.

leider nicht, für das Verständnis die Fehlermeldung die ich gepostet hatte war vom yahka (HomeKit) adapter. der history adapter zeichnet eigentlich nur das auf was der adapter reinschreibt. hab das noch bei keinem anderen adapter gesehen.

ich zeichne alle updates auf die mindestens 500ms gleich bleiben.
hier ein screenshot nach dem neu aufbauen usw
<img width="776" alt="Bildschirmfoto 2021-02-18 um 00 09 06" src="https://user-images.githubusercontent.com/27220902/108279984-c5e67e80-717d-11eb-91a9-7e4a0fa53b55.png">

**Comment by Grizzelbee** [comment]
Hmmmm. Also ich werde den Verdacht nicht los, das wir hier ein Gespenst jagen.
Für mich stellt sich das gerade so dar: Sowohl der yahka-Adapter als auch der dyson-adapter als solche sind in ihrem Verhalten unauffällig. Der History-Adapter zeichnet aber irgendwelche komischen Werte von beiden Adaptern auf. Wenn ich mir die Aufzeichnungen vom dyson so anschaue, sieht das für mich so aus, als würden die Werte manchmal als Zahlen (50 - letzte Zeile) interpretiert und manchmal als String oder auch als Objekt (0050,0050 - vorletzte Zeile). Und immer wenn sie als String/Objekt interpretiert werden, zeigt er die Werte doppelt an. Das ist aktuell das System, das ich dahinter erkenne. Für mich sieht das nach einem gewollten Verhalten des History Adapters aus. Da ich den aber nicht einsetze, kann ich da nicht so viel zu sagen.

**Comment by Grizzelbee** [comment]
`dysonairpurifier.0 | 2021-02-18 08:35:24.942 | debug | (7264) FOUND: fnsp,FanSpeed,Current fan speed,string,true,switch,,[object Object]
-- | -- | -- | --
dysonairpurifier.0 | 2021-02-18 08:35:24.942 | debug | (7264) getDatapoint(fnsp)
dysonairpurifier.0 | 2021-02-18 08:35:24.942 | debug | (7264)  Processing Message:  {"fpwr":"ON","auto":"ON","oscs":"ON","oson":"ON","nmod":"OFF","rhtm":"ON","fnst":"FAN","ercd":"11E1","wacd":"NONE","nmdv":"0004","fnsp":"AUTO","bril":"0002","corf":"ON","cfl
 `
Ich denke, ich habe das Problem gefunden. Es werden tatsächlich gelegentlich Objekte geschriebn, obschon es Werte sein sollten. 
Ich schaue mir das genauer  an.
