### ISSUE TITLE
adapter does no login after dyson changed login procedure on 2021/03/03 (Error 401)

### ISSUE THREAD

**Issue by Day1983** [Grizzelbee/ioBroker.dysonairpurifier#75]
Hallo,

nach einem Neustart vom Raspi4 wird der Adapter leider nicht mehr grün.
Hier die Fehlermeldung.

Hab die Logindaten (Alle Felder) bereits mal neu eingegeben - leider keine Verbesserung.

![image](https://user-images.githubusercontent.com/77491820/109849098-44005600-7c51-11eb-8701-073691756de2.png)

**Comment by Grizzelbee** [comment]
Das habe ich heute schon gelesen. Dyson hat wohl mal wieder die Login Prozedur geändert.
Wir können erst einmal nur abwarten. Aktuell habe ich keine Lösung für das Problem.

**Comment by Grizzelbee** [comment]
Just tested in my development environment and can confirm that the adapter isn't able to login to the dyson cloud after the current major update to the dyson mobile apphas been rolled out. But ... after opening the mobile app once I've been able (the adapter was) to login again. 
So please update your dyson mobile app to the most recent version, open it and try to start the adapter after. This should work.

**Comment by Day1983** [comment]
läuft wieder!

**Comment by viper4gh** [comment]
Ich kann das Verhalten bestätigen, nach iobroker restart lief es nicht.
Auch die CURL Befehle haben nicht geholfen.
Erst nachdem ich einmal die App offen hatte, hat es funktioniert.

Allgemeine Frage:
Wenn die Daten von Dyson beim allerersten mal einrichten abgefragt wurden, ist es dann nötig, das bei jedem Adapter restart wieder zu machen?
Eventuell könnte man in den Settings eine Funktion einbauen, dass man das manuell triggert zum Aktualisieren oder auch beim erstmaligen Gebrauch.
Oder gibt es einen triftigen Grund, dass das bei jedem Adapterstart notwenig ist?

**Comment by Grizzelbee** [comment]
Einen wirklich triftigen Grund gibt es nicht. Nein.
Der Login an der Cloud wird ausschließlich dafür benötigt die dort angemeldeten Geräte und deren (lokale) mqtt credentials abzurufen. Nachdem das erledigt ist, wird ja auch nicht mehr mit der cloud sondern nur noch lokal mit den Geräten kommuniziert. Es hat eher etwas mit Bequemlichkeit und Komfort zu tun. Bequemlichkeit für mich um ein paar Dinge nicht implementieren zu müssen und Komfort für den User um ein paar Dinge nicht manuell ausführen zu müssen.
Der Punkt ist aber eher der: Da es keinen anderen Weg gibt an die mqtt-credentials der Geräte zu kommen, muss der Adapter auf jeden Fall mit der Cloud reden können - und wenn er das kann ist es eigentlich egal wie oft er das tut. Zumal eben neue Geräte aktuell auch nur so erkannt und hinzugefügt werden.
Aber - Ja! Du hast recht: So lange keine neuen Geräte hinzu kommen und ich die einmal gewonnenen Credentials im ioBroker speichere könnte der cloud login kaputt gehen bis er wund ist. Es würde niemanden jucken. ;-)

Der neue Weg für einen funktinierenden Login scheint auch schon gefunden zu sein - ich habe aber noch Bauchschmerzen dabei ihn zu implementieren. Der erfordert nämlich das beim ersten Login eine 2-Faktor-Autentifizierung stattfindet. Will sagen: Man konfiguriert den Adapter, klickt einen Button, bekommt eine Mail mit einem Code , muss diesen Code widerum in die Konfig eintragen und dann sollte das klappen.
Alles in Allem ein Procedere, das ich nicht so cool finde... (ich fürchte nur, das ich keine andere Wahl habe ...)

**Comment by fluke101** [comment]
Hallo ... gibt es schon erste Erfolge bezüglich des Logins? Die 2-Faktor-Autentifizierung wäre für mich voll ok.

**Comment by Grizzelbee** [comment]
@fluke101 Nein. Leider noch nicht. Meine gesammte Zeit wurde von meinem Miele-Adapter aufgefressen. Da ich den aber gerade in die Testphase gegeben habe bin ich zuversichtlich hier bald wieder etwas tun zu können.

**Comment by fluke101** [comment]
Hallo, vielen dank für die Information. Wäre fein wieder einen laufenden Adapter zu haben. Kann man sich für deine Arbeit irgendwie erkenntlich zeigen? gruß fluke

**Comment by Grizzelbee** [comment]
Der Adapter läuft ja an sich, wenn man den Trick anwendet ;)

Ich denke mal über einen donate-button nach. ;)

**Comment by rubberduck1972** [comment]
Hallo, zuerst auch einmal vielen Dank auch von mir für den Adapter. Ich hatte aktuell auch das Problem das sich der Adapter nach einer Wiederherstellung von IOBroker nicht verbunden hat. Sowohl gestern als auch heute konnte ich den Adapter jedoch wieder verbinden, wenn ich die Anmeldedaten (E-Mail und Passwort) manuell und vollständig neu eingegeben habe (keine Autovervollständigung verwenden) und die Adapterkonfigurationsseite mit speichern und schließen verlasse. Läuft jetzt wieder rund.

**Comment by fluke101** [comment]
> Hallo, zuerst auch einmal vielen Dank auch von mir für den Adapter. Ich hatte aktuell auch das Problem das sich der Adapter nach einer Wiederherstellung von IOBroker nicht verbunden hat. Sowohl gestern als auch heute konnte ich den Adapter jedoch wieder verbinden, wenn ich die Anmeldedaten (E-Mail und Passwort) manuell und vollständig neu eingegeben habe (keine Autovervollständigung verwenden) und die Adapterkonfigurationsseite mit speichern und schließen verlasse. Läuft jetzt wieder rund.

Hallo,
bei mir lässt sich der adapter noch immer nicht verbinden :-( bekomme folgende Meldungen:


dysonairpurifier.0 | 2021-04-03 22:25:36.288 | error | (2476) [main()] error: undefined, stack: undefined
-- | -- | -- | --
dysonairpurifier.0 | 2021-04-03 22:25:36.286 | error | (2476) Credentials used for login: User:[xxxxxxx] - Password:[xxxxxxx] - Country:[at]
dysonairpurifier.0 | 2021-04-03 22:25:36.285 | error | (2476) Error: Unable to authenticate user! Your credentials seem to be invalid. Please double check and fix them.
dysonairpurifier.0 | 2021-04-03 22:25:36.284 | error | (2476) Error during dyson cloud API login:Error: Request failed with status code 401, Callstack: Error: Request failed with status code 401 at createError (/opt/iobroker/node_modules/axios/lib/cor
dysonairpurifier.0 | 2021-04-03 22:25:35.844 | info | (2476) Result from API-Status request -> Account is: ACTIVE
dysonairpurifier.0 | 2021-04-03 22:25:35.307 | info | (2476) Signing in into dyson cloud API ...
dysonairpurifier.0 | 2021-04-03 22:25:35.252 | info | (2476) starting. Version 0.8.1 in /opt/iobroker/node_modules/iobroker.dysonairpurifier, node: v12.20.2, js-controller: 3.2.16

hat jemand einen rat?

gruß fluke

**Comment by Grizzelbee** [comment]
@fluke101 
Der Hier weiter oben: [https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/75#issuecomment-790437378](https://github.com/Grizzelbee/ioBroker.dysonairpurifier/issues/75#issuecomment-790437378) beschriebene Workaround funktioniert meines Wissens nach noch immer. Damit solltest DU den Adapter zum Arbeiten bringen können, bis ich einen Fix entwickelt habe.
