### ISSUE TITLE
Installations Anleitung ist fehlerhaft.

### ISSUE THREAD

**Issue by FrodoVDR** [Grizzelbee/ioBroker.dysonairpurifier#80]
Hallo egal ober über die iobroker Webseite oder der Kommando Zeile die Installation bricht immer ab:
`$ ./iobroker url "https://github.com/Grizzelbee/ioBroker.dysonairpurifier.git" --debug
install Grizzelbee/ioBroker.dysonairpurifier#f8d4da3beed3635d25c89ba6740378a89c01de77
NPM version: 6.14.11
npm install Grizzelbee/ioBroker.dysonairpurifier#f8d4da3beed3635d25c89ba6740378a89c01de77 --loglevel error --prefix "/opt/iobroker" (System call)
npm ERR! premature close

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-03-20T10_26_23_405Z-debug.log
ERROR: host.iobroker1 Cannot install Grizzelbee/ioBroker.dysonairpurifier#f8d4da3beed3635d25c89ba6740378a89c01de77: 1
ERROR: process exited with code 25`
An der Konsole sieht man auch warum:
`iobroker@iobroker1:/opt/iobroker$ npm install ioBroker.dysonairpurifier
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/ioBroker.dysonairpurifier - Not found
npm ERR! 404
npm ERR! 404  'ioBroker.dysonairpurifier@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2021-03-20T10_30_39_980Z-debug.log
`
Bitte ändere doch bei Gelegenheit die Anleitung entsprechend ab:
`npm install iobroker.dysonairpurifier`

Per git bekomme ich es gar nicht hin, weil der Name ein großes "B" beinhaltet.

**Comment by Grizzelbee** [comment]
Hallo Frodo,

vielenDank für die Info. Ich werde das gelegentlich korrigieren.
Es ist richtig das bei npm kein großes "B" vorkommen darf. Bei git wiederum muss es drin sein.
Bedeutet: Wenn du in der AdapterAnsicht auf das Katzen-Icon klickst und diese URL angibst: https://github.com/Grizzelbee/ioBroker.dysonairpurifier.git müsste es klappen.
