### ISSUE TITLE
Improve Support for Dyson Pure Hot+Cool (Heater)

### ISSUE THREAD

**Issue by janku-88** [Grizzelbee/ioBroker.dysonairpurifier#92]
Hallo,

erstmal vielen Dank für die Arbeit. Was der Apdater schon kann ist sehr gut.
Das lesen der ganzen Werte läuft Problemlos.
 
Beim kauf von dem Teil habe ich nicht daran gedacht das mal irgendwann in ioBroker einzubinden.
Aber das lief dann bei einem "mal schauen ob's geht Test" so easy, dass ich jetzt doch gerne die ein oder andere Funktion darauf aufbauen würde.

Leider habe ich das Problem, dass das Senden der Objekte für den Heat Mode nicht funktioniert.
Ich verändere die Objekte über Admin/Objekte. 
"MainPower" und "NightMode" lassen sich ohne Probleme schalten (Gerät reagiert auf die gesendeten Befehle und der eingetragene Objektwert bleibt stehen).
Bei "HeaterMode" und "TemperatureTarget" reagiert das Gerät nicht auf Änderungen der Objektes und der eingetragene Wert wird, abhängig vom Polling Interval, mit dem Gerätewert überschrieben.
Laut Log wird der Steuerbefehl bei Änderung der Heat-Objekte, wie bei den anderen, an das Gerät gesendet. 

dysonairpurifier.0 | 2021-04-13 18:35:50.306 | info | (1012) SENDING this data to device (A1A-EU-MNA5135A): {"hmax":"0563"}
dysonairpurifier.0 | 2021-04-13 18:35:46.646 | info | (1012) SENDING this data to device (A1A-EU-MNA5135A): {"hmod":"ON"}

Wenn der Heat Mode über die Handy App eingeschaltet wird oder die Solltemperatur geändert, wird der Wert von ioBroker korrekt gelesen.

Da das ganze im Prinzip Funktioniert komme ich hier nicht weiter und wäre für Hilfe dankbar.
Falls weitere Infos benötigt werden oder irgendwelche Tests, kein Problem.

Eine Fehlerquelle kann ich meinerseits leider nicht ganz ausschließen.
- Autoupdate auf dem Gerät war deaktiviert. Das vom Gerät gelesene iobroker Objekt "Firmware.NewVersionAvailable" steht auf "True". Manuells Firmware-Update über die App erzeugt nur eine Fehlermeldung und mit aktiviertem Autoupdate passiert auch kein Update. Möglicherweise gibt es eine FW neuer als die installierte "ECG2PF.30.06.003.0002", in der irgendwas anders ist.
Ansonsten ioBroker komplett auf aktuellsten Versionen

Grüße
Jan

**Comment by Grizzelbee** [comment]
Hallo Jan,

auch wenn du Fehler deinerseits nichts ausschließen kannst ... ich schon.
Die Entwicklung des Adapters wurde von mir zu einem Zeitpunkt unterbrochen als die Unterstützung für die Heater und Humidifier gerade in der Entstehung war. Sie ist also in Bruchstücken implementiert, aber nicht getestet. Wenn Du mir mit Tests helfen möchtest wäre das super.
Nachdem ich die Arbeiten an meinem Miele-Adapter gerade abgeschlossen habe, nehme ich gerade die Arbeit am dyson-Adapter wieder auf.
Als erstes will ich die 2Faktor Autentifizierung einbauen und dann die Unterstützung für Heater und Humidifier ausbauen.
Soweit zumindest aktuell der Plan.

**Comment by janku-88** [comment]
Das klingt gut. 
Bei den Tests zu unterstützen würde mich interessieren.
Je nachdem wie es dann zeitlich passt mache ich das gerne.

**Comment by janku-88** [comment]
Das klingt gut. 
Bei den Tests zu unterstützen würde mich interessieren.
Je nachdem wie es dann zeitlich passt mache ich das gerne.

**Comment by Grizzelbee** [comment]
Ich wundere mich gerade das du den issue schließt. 
Keine Lust mehr zu testen? 
So weit ich weiß funktioniert doch noch nicht alles.

**Comment by janku-88** [comment]
Moin, ne, alles gut.
Irgendwie wat die Seite noch auf, und dann Stand meine Antwort auf einmal
zweimal da. Eigentlich wollte ich nur eine wieder weg machen.
Klassische Fehlbedienung :)

Grizzelbee ***@***.***> schrieb am Mi., 21. Apr. 2021, 21:48:

**Comment by Grizzelbee** [comment]
Wie sieht es aus? Funktioniert alles wie gewünscht und wir können den issue zu machen, oder sind noch Anpassungen für die Heater notwendig?

**Comment by Grizzelbee** [comment]
Geschlossen aufgrund fehlender Beteiligung.
