### ISSUE TITLE
TP02: DustIndex not working

### ISSUE THREAD

**Issue by Grizzelbee** [Grizzelbee/ioBroker.dysonairpurifier#94]
Ich ebenfalls den TP02 und finde es interessant, dass bei dir mehr Sensoren angezeigt werden, als bei mir. Ich kann lediglich auf Dust und VOC zugreifen, was die Luftverschmutzung betrifft. Der Datenpunkt DustIndex ist bei mir aber ohne Funktion. Steht immer auf Good(0). Wie ist das bei dir? Ändern sich Dir die Werte für Feinstaub und DustIndex?
https://forum.iobroker.net/post/614191

**Comment by mrbjoernson** [comment]
Super, danke fürs aufnehmen von dem Bug.
